### Webscrapping with Pandas pd.read_html()  + ODBC on SQL Server with pyodbc

#### Source : Wikipedia / IFSC Climbing WorldWide Championships (International Federation of Sport Climbing)

The IFSC Climbing World Championships are the biennial Worldwide championship for competition climbing organized by the  IFSC. The first competition was held in Frankfurt in 1991

This event determines the male and female world champions in the 3 disciplines of competition climbing:

competition LEADING, competition BOULDERING, and competition SPEED CLIMBING. Since 2012, a COMBINED RANKING is also determined, for climbers competing in all disciplines, and additional medals are awarded based on that ranking.

IMPORTANT : #1 Not to be confused with IFSC Climbing World Cup

IMPORTANT : #2 IFSC Climbing World YOUTH Championships for climbers UNDER AGE OF 20

In [2]:
import numpy as np
import pandas as pd
# Beautifulsoup already installed into Anaconda environment

# Librairy PyODBC for SQL Server connection
import os
import pyodbc
# setup SQL Server connection session
server = '-PCSJN\DATAVIZ'  
database = 'Climbing_Staging'
connection_string= (
                    'DRIVER={SQL Server};SERVER='
                     + server
                     + ';DATABASE='
                     + database 
                     + ';Trusted_Connection=yes'                  
                    )

# Function for injecting dataframe content into SQL Server Table
def template_SQL_insert_values(table_name,dict):
    
    columns = "("
    for k in dict.keys():
        columns += str(k) + ','
    columns = columns[:-1] ### remove last comma
    columns += ")"
    
    req = f"""INSERT INTO {table_name} {columns} VALUES {tuple(dict.values())}"""
    return req

In [3]:
### url
Wiki_IFSC_Climbing_World_Championships = "https://en.wikipedia.org/wiki/IFSC_Climbing_World_Championships"
### récuperer toutes les tables html vu sur le site (url)
Dataset_Wiki_IFSC_Climbing_World_Championships = pd.read_html(Wiki_IFSC_Climbing_World_Championships)
type(Dataset_Wiki_IFSC_Climbing_World_Championships), len(Dataset_Wiki_IFSC_Climbing_World_Championships)

(list, 30)

##### on récupère 1 list de 30 élts

In [94]:
type(Dataset_Wiki_IFSC_Climbing_World_Championships[0])

pandas.core.frame.DataFrame

##### > Chaque élt est un DataFrame Pandas
##### ? Quel est le contenu chacun des 30 dataframes ? Lesquelles nous interessent ?

In [95]:
Dataset_Wiki_IFSC_Climbing_World_Championships[0]

                   IFSC Climbing World Championships  \
                                             Seasons
0  1991 1993 1995 1997 1999 2001 2003 2005 2007 2...
1                                        Disciplines
2                     Lead Bouldering Speed Combined
3                                   Most gold medals
4                                 Janja Garnbret (8)


                                           Seasons.1
0  1991 1993 1995 1997 1999 2001 2003 2005 2007 2...
1                                        Disciplines
2                     Lead Bouldering Speed Combined
3                                   Most gold medals
4                                 Janja Garnbret (8)

######## [0] is dataset of summarized data about Climbing Worldwide championships dataset

In [4]:
Dataset_Wiki_IFSC_Climbing_World_Championships[1]

   Edition  Year    Location                Date(s) Disciplines              \
   Edition  Year    Location                Date(s)       Event  L  S  B  C
0        1  1991   Frankfurt            1–2 October           2  X  X  -  -
1        2  1993   Innsbruck            29–30 April           2  X  X  -  -
2        3  1995      Geneva                5–6 May           2  X  X  -  -
3        4  1997       Paris  31 January–1 February           2  X  X  -  -
4        5  1999  Birmingham           2–3 December           2  X  X  -  -
5        6  2001  Winterthur          5–8 September           3  X  X  X  -
6        7  2003    Chamonix              9–13 July           3  X  X  X  -
7        8  2005      Munich               1–5 July           3  X  X  X  -
8        9  2007      Avilés        17–23 September           3  X  X  X  -
9       10  2009      Xining       30 June – 5 July           4  X  X  X  -
10      11  2011        Arco             15–24 July           4  X  X  X  -
11      12  2012       Paris        12–16 September           5  X  X  X  X
12      13  2014      Munich           21–23 August           1  -  -  X  -
13      13  2014       Gijón         8–14 September           4  X  X  -  X
14      14  2016       Paris        14–18 September           5  X  X  X  X
15      15  2018   Innsbruck         6–16 September           5  X  X  X  X
16      16  2019    Briançon             16–17 July           1  -  -  -  -
17      16  2019    Hachioji           11–21 August           4  X  X  X  X
18      17  2021      Moscow        15–21 September           5  X  X  X  X
19      18  2023        Bern            1–12 August           5  X  X  X  X
20      19  2025   Seoul[27]                    NaN           5  X  X  X  X

        Athletes Nations                                            Website  \
   Para Athletes Nations                                            Website
0     -    110.0    22.0                                                NaN
1     -    127.0    23.0                                                NaN
2     -    135.0    24.0                                                NaN
3     -    153.0    26.0                                                NaN
4     -    180.0    30.0                                                NaN
5     -    198.0    25.0                                                NaN
6     -    241.0    34.0                                                NaN
7     -    318.0    51.0                                                NaN
8     -    302.0    50.0                                                NaN
9     -    219.0    44.0                                                NaN
10    X    374.0    56.0                                                NaN
11    X    331.0    56.0                                                NaN
12    -    509.0    52.0                                                [1]
13    X    509.0    52.0                                                [2]
14    X    533.0    53.0                                                [3]
15    X    834.0    58.0                                                [4]
16    X      NaN     NaN                                                NaN
17    -    253.0    39.0  [5] Archived 20 April 2021 at the Wayback Machine
18    X      NaN     NaN                                                NaN
19    X      NaN     NaN                                                [6]
20    X      NaN     NaN                                                NaN

          Notes
          Notes
0           [8]
1           [9]
2          [10]
3          [11]
4          [12]
5          [13]
6          [14]
7          [15]
8          [16]
9          [17]
10         [18]
11      [19][1]
12      [20][2]
13      [20][2]
14  [21][3][22]
15      [23][4]
16          NaN
17     [24][25]
18         [26]
19          NaN
20          NaN

In [5]:
Dataset_Wiki_IFSC_Climbing_World_Championships[1].columns

MultiIndex([(    'Edition',  'Edition'),
            (       'Year',     'Year'),
            (   'Location', 'Location'),
            (    'Date(s)',  'Date(s)'),
            ('Disciplines',    'Event'),
            ('Disciplines',        'L'),
            ('Disciplines',        'S'),
            ('Disciplines',        'B'),
            ('Disciplines',        'C'),
            ('Disciplines',     'Para'),
            (   'Athletes', 'Athletes'),
            (    'Nations',  'Nations'),
            (    'Website',  'Website'),
            (      'Notes',    'Notes')],
           )

######## [1] is the List of Climbing Worldwide Championships > NOT to Discard

In [7]:
# Delete Multi Index
# Replace Date par Period (car SQL à avoir format Date, non applicable ici)
Dataset_Wiki_IFSC_Climbing_World_Championships[1].columns = ['Edition','Year','Location','Period','Event','LEAD','SPEED','BOULDER','COMBINED','PARA','Athletes','Nations','Website','Notes']
Dataset_Wiki_IFSC_Climbing_World_Championships[1]

,Edition,Year,Location,Period,Event,LEAD,SPEED,BOULDER,COMBINED,PARA,Athletes,Nations,Website,Notes
0,1,1991,Frankfurt,1–2 October,2,X,X,-,-,-,110.0,22.0,NaN,[8]
1,2,1993,Innsbruck,29–30 April,2,X,X,-,-,-,127.0,23.0,NaN,[9]
2,3,1995,Geneva,5–6 May,2,X,X,-,-,-,135.0,24.0,NaN,[10]
3,4,1997,Paris,31 January–1 February,2,X,X,-,-,-,153.0,26.0,NaN,[11]
4,5,1999,Birmingham,2–3 December,2,X,X,-,-,-,180.0,30.0,NaN,[12]
5,6,2001,Winterthur,5–8 September,3,X,X,X,-,-,198.0,25.0,NaN,[13]
6,7,2003,Chamonix,9–13 July,3,X,X,X,-,-,241.0,34.0,NaN,[14]
7,8,2005,Munich,1–5 July,3,X,X,X,-,-,318.0,51.0,NaN,[15]
8,9,2007,Avilés,17–23 September,3,X,X,X,-,-,302.0,50.0,NaN,[16]
9,10,2009,Xining,30 June – 5 July,4,X,X,X,-,-,219.0,44.0,NaN,[17]
10,11,2011,Arco,15–24 July,4,X,X,X,-,X,374.0,56.0,NaN,[18]
11,12,2012,Paris,12–16 September,5,X,X,X,X,X,331.0,56.0,NaN,[19][1]
12,13,2014,Munich,21–23 August,1,-,-,X,-,-,509.0,52.0,[1],[20][2]
13,13,2014,Gijón,8–14 September,4,X,X,-,X,X,509.0,52.0,[2],[20][2]
14,14,2016,Paris,14–18 September,5,X,X,X,X,X,533.0,53.0,[3],[21][3][22]
15,15,2018,Innsbruck,6–16 September,5,X,X,X,X,X,834.0,58.0,[4],[23][4]
16,16,2019,Briançon,16–17 July,1,-,-,-,-,X,NaN,NaN,NaN,NaN
17,16,2019,Hachioji,11–21 August,4,X,X,X,X,-,253.0,39.0,[5] Archived 20 April 2021 at the Wayback Machine,[24][25]
18,17,2021,Moscow,15–21 September,5,X,X,X,X,X,NaN,NaN,NaN,[26]
19,18,2023,Bern,1–12 August,5,X,X,X,X,X,NaN,NaN,[6],NaN
20,19,2025,Seoul[27],NaN,5,X,X,X,X,X,NaN,NaN,NaN,NaN

In [8]:
Dataset_Wiki_IFSC_Climbing_World_Championships[1].columns

Index(['Edition', 'Year', 'Location', 'Period', 'Event', 'LEAD', 'SPEED',
       'BOULDER', 'COMBINED', 'PARA', 'Athletes', 'Nations', 'Website',
       'Notes'],
      dtype='object')

In [9]:
Dataset_Wiki_IFSC_Climbing_World_Championships[1].dtypes

Edition       int64
Year          int64
Location     object
Period       object
Event         int64
LEAD         object
SPEED        object
BOULDER      object
COMBINED     object
PARA         object
Athletes    float64
Nations     float64
Website      object
Notes        object
dtype: object

In [11]:
Wiki_IFSC_Climbing_World_Championships_Edition_List_Df1 = Dataset_Wiki_IFSC_Climbing_World_Championships[1]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championships_Edition_List_Df1
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Edition INT,
                                        Year INT,
                                        Location VARCHAR(100),
                                        Period VARCHAR(50),
                                        Event INT,
                                        LEAD VARCHAR(50),
                                        SPEED VARCHAR(50),
                                        BOULDER VARCHAR(50),
                                        COMBINED VARCHAR(50), 
                                        PARA VARCHAR(50),
                                        Athletes FLOAT(50),
                                        Nations FLOAT(50),
                                        Website VARCHAR(50), 
                                        Notes VARCHAR(50)                                                           
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championships_Edition_List_Df1.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championships_Edition_List_Df1',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

err: ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'nan'. (207) (SQLExecDirectW)")

4 Disciplines (L : Lead / S : Speed / B : Bouldering / C : Combined ) + Para (?) : From 1991 : Lead and Speed. from 2001 : Boulder(ing). from 2011 : Combined and (?)

In [99]:
Dataset_Wiki_IFSC_Climbing_World_Championships[2]

                   Rank               Nation  Gold  Silver  Bronze  Total
0                     1               Russia    16      14      23     53
1                     2              Austria    15       7       8     30
2                     3               France    14      17      17     48
3                     4              Ukraine    11       7       5     23
4                     5             Slovenia     9       7       5     21
5                     6       Czech Republic     6      10       4     20
6                     7                Japan     6       9       8     23
7                     8                Italy     6       1       2      9
8                     9               Poland     5       4       9     18
9                    10                China     5       4       1     10
10                   11                Spain     4       5       0      9
11                   12        United States     3       9       4     16
12                   13          South Korea     3       5       4     12
13                   14          Switzerland     3       1       5      9
14                   15               Canada     3       1       0      4
15                   16              Belgium     2       6       0      8
16                   17              Germany     2       5       9     16
17                   18                 Iran     1       1       2      4
18                   19            Indonesia     1       0       1      2
19                   20           Kazakhstan     0       1       3      4
20                   21            Venezuela     0       1       0      1
21                   22        Great Britain     0       0       4      4
22                   23               Serbia     0       0       2      2
23                   24          Netherlands     0       0       1      1
24  Totals (24 entries)  Totals (24 entries)   115     115     117    347

[2] is about Worldwide Countries' Ranking (M/W mixed = 'Total') in Climbing Worldwide Championships (based on medals points)

In [6]:
Dataset_Wiki_IFSC_Climbing_World_Championships[2].iloc[0,1] = 'Fédération de Russie'
Dataset_Wiki_IFSC_Climbing_World_Championships[2].iloc[1,1] = 'Autriche'
Dataset_Wiki_IFSC_Climbing_World_Championships[2].iloc[2,1] = 'France'
Dataset_Wiki_IFSC_Climbing_World_Championships[2].iloc[3,1] = 'Ukraine'
Dataset_Wiki_IFSC_Climbing_World_Championships[2].iloc[4,1] = 'Slovénie'
Dataset_Wiki_IFSC_Climbing_World_Championships[2].iloc[5,1] = 'République tchèque'
Dataset_Wiki_IFSC_Climbing_World_Championships[2].iloc[6,1] = 'Japon'
Dataset_Wiki_IFSC_Climbing_World_Championships[2].iloc[7,1] = 'Italie'
Dataset_Wiki_IFSC_Climbing_World_Championships[2].iloc[8,1] = 'Pologne'
Dataset_Wiki_IFSC_Climbing_World_Championships[2].iloc[9,1] = 'Chine'
Dataset_Wiki_IFSC_Climbing_World_Championships[2].iloc[9,1] = 'Espagne'

In [7]:
Dataset_Wiki_IFSC_Climbing_World_Championships[2]

                   Rank                Nation  Gold  Silver  Bronze  Total
0                     1  Fédération de Russie    16      14      23     53
1                     2              Autriche    15       7       8     30
2                     3                France    14      17      17     48
3                     4               Ukraine    11       7       5     23
4                     5              Slovénie     9       7       5     21
5                     6    République tchèque     6      10       4     20
6                     7                 Japon     6       9       8     23
7                     8                Italie     6       1       2      9
8                     9               Pologne     5       4       9     18
9                    10               Espagne     5       4       1     10
10                   11                 Spain     4       5       0      9
11                   12         United States     3       9       4     16
12                   13           South Korea     3       5       4     12
13                   14           Switzerland     3       1       5      9
14                   15                Canada     3       1       0      4
15                   16               Belgium     2       6       0      8
16                   17               Germany     2       5       9     16
17                   18                  Iran     1       1       2      4
18                   19             Indonesia     1       0       1      2
19                   20            Kazakhstan     0       1       3      4
20                   21             Venezuela     0       1       0      1
21                   22         Great Britain     0       0       4      4
22                   23                Serbia     0       0       2      2
23                   24           Netherlands     0       0       1      1
24  Totals (24 entries)   Totals (24 entries)   115     115     117    347

In [13]:
Dataset_Wiki_IFSC_Climbing_World_Championships[2].dtypes

Rank      object
Nation    object
Gold       int64
Silver     int64
Bronze     int64
Total      int64
dtype: object

In [8]:
Wiki_IFSC_Climbing_World_Championships_Countries_Total_Ranking_Df2 = Dataset_Wiki_IFSC_Climbing_World_Championships[2].head(10)

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championships_Countries_Total_Ranking_Df2
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Rank VARCHAR(50),
                                        Nation VARCHAR(50),
                                        Gold INT,
                                        Silver INT,
                                        Bronze INT,
                                        Total INT                                                                  
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championships_Countries_Total_Ranking_Df2.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championships_Countries_Total_Ranking_Df2',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [101]:
Dataset_Wiki_IFSC_Climbing_World_Championships[3]

,Year,Gold,Silver,Bronze
0,1991,François Legrand,Yuji Hirayama,Guido Köstermeyer [de]
1,1993,François Legrand (2),Stefan Glowacz,Yuji Hirayama
2,1995,François Legrand (3),Arnaud Petit [fr],Elie Chevieux [de]
3,1997,François Petit,Chris Sharma,François Legrand
4,1999,Bernardino Lagni [es],Yuji Hirayama,Maksym Petrenko
5,2001,Gérôme Pouvreau [fr],Tomáš Mrázek,François Petit
6,2003,Tomáš Mrázek,Patxi Usobiaga Lakunza,David Caude [fr]
7,2005,Tomáš Mrázek (2),Patxi Usobiaga Lakunza,Alexandre Chabot
8,2007,Ramón Puigblanque,Patxi Usobiaga Lakunza,Cédric Lachat [fr] Tomáš Mrázek Jorg Verhoev...
9,2009,Patxi Usobiaga Lakunza,Adam Ondra,David Lama
10,2011,Ramón Puigblanque (2),Jakob Schubert,Adam Ondra
11,2012,Jakob Schubert,Sean McColl,Adam Ondra
12,2014,Adam Ondra,Ramón Puigblanque,Sachi Amma
13,2016,Adam Ondra (2),Jakob Schubert,Gautier Supper [fr]
14,2018,Jakob Schubert (2),Adam Ondra,Alexander Megos
15,2019,Adam Ondra (3),Alexander Megos,Jakob Schubert
16,2021,Jakob Schubert (3),Luka Potočar,Hamish McArthur
17,2023,Jakob Schubert (4),Sorato Anraku,Alexander Megos

[3] is about Men Medal winner full names of Climbing Worldwide Championships in Disciplin LEAD

In [24]:
Dataset_Wiki_IFSC_Climbing_World_Championships[3].dtypes

Year       int64
Gold      object
Silver    object
Bronze    object
dtype: object

In [67]:
Wiki_IFSC_Climbing_World_Championships_Medal_Men_Lead_Df3 = Dataset_Wiki_IFSC_Climbing_World_Championships[3]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championships_Medal_Men_Lead_Df3
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championships_Medal_Men_Lead_Df3.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championships_Medal_Men_Lead_Df3',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [38]:
Dataset_Wiki_IFSC_Climbing_World_Championships[4]

,Year,Gold,Silver,Bronze
0,1991,Hans Florine,Jacky Godoffe [cs],Kairat Rachmetov [cs]
1,1993,Vladimir Netsvetaïev [fr],Serik Kazbekov [cs],Yevgen Kryvosheytsev [cs]
2,1995,Andrey Vedenmeer [fr],Milan Benian [cs],Vladimir Netsvetaïev [fr]
3,1997,Daniel Andrada [es],Yevgen Kryvosheytsev [cs],Dmitrij Byčkov [cs]
4,1999,Vladimir Zakharov [es],Vladimir Netsvetaïev [fr],Alexey Gadeev
5,2001,Maksym Styenkovyy,Vladimir Zakharov [es],Tomasz Oleksy [pl]
6,2003,Maksym Styenkovyy (2),Tomasz Oleksy [pl],Alexandr Pechekhonov [fr]
7,2005,Evgeny Vaitcekhovsky,Maksym Styenkovyy,Sergey Sinitsyn [de]
8,2007,Zhong Qixin,Manuel Escobar [cs],Sergey Sinitsyn [de]
9,2009 (10 m),Zhong Qixin (2),Alexandr Nigmatulin [cs],Ivan Novikov [es]
10,2009 (15 m)[28],Zhong Qixin (3),Sergey Abdrakhmanov [pl],Ning Zhang
11,2011,Zhong Qixin (4),Stanislav Kokorin,Danyil Boldyrev
12,2012,Zhong Qixin (5),Libor Hroza [cs],Dmitry Timofeev [cs]
13,2014,Danyil Boldyrev,Stanislav Kokorin,Reza Alipour
14,2016,Marcin Dzieński,Reza Alipour,Alexandr Shikov [es]
15,2018,Reza Alipour,Bassa Mawem,Stanislav Kokorin
16,2019,Ludovico Fossali,Jan Kříž [cs],Stanislav Kokorin
17,2021,Danyil Boldyrev (2),Erik Noya Cardona,Noah Bratschi
18,2023,Matteo Zurloni,Long Jinbao,Rahmad Adi Mulyono

[4] is about Men Medal winner full names of Climbing Worldwide Championships in Disciplin SPEED

In [61]:
Dataset_Wiki_IFSC_Climbing_World_Championships[4].iloc[9,:]

Year                   2009 (10 m)
Gold               Zhong Qixin (2)
Silver    Alexandr Nigmatulin [cs]
Bronze           Ivan Novikov [es]
Name: 9, dtype: object

In [63]:
Dataset_Wiki_IFSC_Climbing_World_Championships[4].iloc[10,:]

Year               2009 (15 m)[28]
Gold               Zhong Qixin (3)
Silver    Sergey Abdrakhmanov [pl]
Bronze                  Ning Zhang
Name: 10, dtype: object

2 X en 2009 (10 et 15m). Je supprime les distances. et je vide la ligne 10

In [64]:
# Cleansing Year : delete [ ] 
Dataset_Wiki_IFSC_Climbing_World_Championships[4].iloc[9,0] = '2009'
Dataset_Wiki_IFSC_Climbing_World_Championships[4].iloc[10,:] = '-'

In [65]:
Dataset_Wiki_IFSC_Climbing_World_Championships[4]

,Year,Gold,Silver,Bronze
0,1991,Hans Florine,Jacky Godoffe [cs],Kairat Rachmetov [cs]
1,1993,Vladimir Netsvetaïev [fr],Serik Kazbekov [cs],Yevgen Kryvosheytsev [cs]
2,1995,Andrey Vedenmeer [fr],Milan Benian [cs],Vladimir Netsvetaïev [fr]
3,1997,Daniel Andrada [es],Yevgen Kryvosheytsev [cs],Dmitrij Byčkov [cs]
4,1999,Vladimir Zakharov [es],Vladimir Netsvetaïev [fr],Alexey Gadeev
5,2001,Maksym Styenkovyy,Vladimir Zakharov [es],Tomasz Oleksy [pl]
6,2003,Maksym Styenkovyy (2),Tomasz Oleksy [pl],Alexandr Pechekhonov [fr]
7,2005,Evgeny Vaitcekhovsky,Maksym Styenkovyy,Sergey Sinitsyn [de]
8,2007,Zhong Qixin,Manuel Escobar [cs],Sergey Sinitsyn [de]
9,2009,Zhong Qixin (2),Alexandr Nigmatulin [cs],Ivan Novikov [es]
10,-,-,-,-
11,2011,Zhong Qixin (4),Stanislav Kokorin,Danyil Boldyrev
12,2012,Zhong Qixin (5),Libor Hroza [cs],Dmitry Timofeev [cs]
13,2014,Danyil Boldyrev,Stanislav Kokorin,Reza Alipour
14,2016,Marcin Dzieński,Reza Alipour,Alexandr Shikov [es]
15,2018,Reza Alipour,Bassa Mawem,Stanislav Kokorin
16,2019,Ludovico Fossali,Jan Kříž [cs],Stanislav Kokorin
17,2021,Danyil Boldyrev (2),Erik Noya Cardona,Noah Bratschi
18,2023,Matteo Zurloni,Long Jinbao,Rahmad Adi Mulyono

In [25]:
Dataset_Wiki_IFSC_Climbing_World_Championships[4].dtypes

Year      object
Gold      object
Silver    object
Bronze    object
dtype: object

In [66]:
Wiki_IFSC_Climbing_World_Championships_Medal_Men_Speed_Df4 = Dataset_Wiki_IFSC_Climbing_World_Championships[4]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championships_Medal_Men_Speed_Df4
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(50),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championships_Medal_Men_Speed_Df4.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championships_Medal_Men_Speed_Df4',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [105]:
Dataset_Wiki_IFSC_Climbing_World_Championships[5]

    Year                     Gold                Silver                Bronze
0   2001      Mauro Calibani [it]  Frédéric Tuscan [cs]        Christian Core
1   2003           Christian Core          Jérôme Meyer    Tomasz Oleksy [pl]
2   2005   Salavat Rachmetov [cs]     Kilian Fischhuber  Gérôme Pouvreau [fr]
3   2007      Dmitri Sarafutdinov   Martin Stráník [cs]    Cédric Lachat [fr]
4   2009           Alexey Rubtsov  Rustam Gelmanov [cs]    David Barrans [pl]
5   2011  Dmitri Sarafutdinov (2)            Adam Ondra  Rustam Gelmanov [cs]
6   2012  Dmitri Sarafutdinov (3)     Kilian Fischhuber  Rustam Gelmanov [cs]
7   2014               Adam Ondra         Jernej Kruder             Jan Hojer
8   2016           Tomoa Narasaki            Adam Ondra          Manuel Cornu
9   2018               Kai Harada          Jongwon Chon   Gregor Vezonik [cs]
10  2019       Tomoa Narasaki (2)        Jakob Schubert         Yannick Flohé
11  2021             Kokoro Fujii        Tomoa Narasaki          Manuel Cornu
12  2023            Mickael Mawem         Mejdi Schalck            Dohyun Lee

[5] is about Men Medal winner full names of Climbing Worldwide Championships in Disciplin BOULDERING

In [26]:
Dataset_Wiki_IFSC_Climbing_World_Championships[5].dtypes

Year       int64
Gold      object
Silver    object
Bronze    object
dtype: object

In [58]:
Wiki_IFSC_Climbing_World_Championships_Medal_Men_Bouldering_Df5 = Dataset_Wiki_IFSC_Climbing_World_Championships[5]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championships_Medal_Men_Bouldering_Df5
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championships_Medal_Men_Bouldering_Df5.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championships_Medal_Men_Bouldering_Df5',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [107]:
Dataset_Wiki_IFSC_Climbing_World_Championships[6]

          Year                Gold               Silver                 Bronze
0      2012[1]         Sean McColl  Thomas Tauporn [de]     Cédric Lachat [fr]
1      2014[2]     Sean McColl (2)            Jan Hojer      Alban Levier [es]
2  2016[3][22]     Sean McColl (3)         Manuel Cornu  David Firnenburg [cs]
3      2018[4]      Jakob Schubert           Adam Ondra              Jan Hojer
4         2019      Tomoa Narasaki       Jakob Schubert      Rishat Khaibullin
5         2021       Yannick Flohé       Philipp Martin         Fedir Samoilov
6         2023  Jakob Schubert (2)          Colin Duffy         Tomoa Narasaki

[6] is about Men Medal winner full names of Climbing Worldwide Championships in Disciplin COMBINED

In [53]:
Dataset_Wiki_IFSC_Climbing_World_Championships[6].iloc[0,:]

Year                  2012[1]
Gold              Sean McColl
Silver    Thomas Tauporn [de]
Bronze     Cédric Lachat [fr]
Name: 0, dtype: object

In [54]:
# Cleansing Year : delete [ ] 
Dataset_Wiki_IFSC_Climbing_World_Championships[6].iloc[0,0] = '2012'
Dataset_Wiki_IFSC_Climbing_World_Championships[6].iloc[1,0] = '2014'
Dataset_Wiki_IFSC_Climbing_World_Championships[6].iloc[2,0] = '2016'
Dataset_Wiki_IFSC_Climbing_World_Championships[6].iloc[3,0] = '2018'

In [55]:
Dataset_Wiki_IFSC_Climbing_World_Championships[6]

   Year                Gold               Silver                 Bronze
0  2012         Sean McColl  Thomas Tauporn [de]     Cédric Lachat [fr]
1  2014     Sean McColl (2)            Jan Hojer      Alban Levier [es]
2  2016     Sean McColl (3)         Manuel Cornu  David Firnenburg [cs]
3  2018      Jakob Schubert           Adam Ondra              Jan Hojer
4  2019      Tomoa Narasaki       Jakob Schubert      Rishat Khaibullin
5  2021       Yannick Flohé       Philipp Martin         Fedir Samoilov
6  2023  Jakob Schubert (2)          Colin Duffy         Tomoa Narasaki

In [27]:
Dataset_Wiki_IFSC_Climbing_World_Championships[6].dtypes

Year      object
Gold      object
Silver    object
Bronze    object
dtype: object

In [56]:
Wiki_IFSC_Climbing_World_Championships_Medal_Men_Combined_Df6 = Dataset_Wiki_IFSC_Climbing_World_Championships[6]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championships_Medal_Men_Combined_Df6
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(50),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championships_Medal_Men_Combined_Df6.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championships_Medal_Men_Combined_Df6',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [109]:
Dataset_Wiki_IFSC_Climbing_World_Championships[7]

    Year                Gold               Silver                    Bronze
0   1991      Susi Good [fr]   Isabelle Patissier          Robyn Erbesfield
1   1993  Susi Good [fr] (2)     Robyn Erbesfield        Isabelle Patissier
2   1995    Robyn Erbesfield  Laurence Guyon [fr]                Liv Sansoz
3   1997          Liv Sansoz       Muriel Sarkany       Marietta Uhden [de]
4   1999      Liv Sansoz (2)       Muriel Sarkany  Yelena Ovchinnikova [cs]
5   2001  Martina Čufar [fr]       Muriel Sarkany        Chloé Minoret [fr]
6   2003      Muriel Sarkany   Emilie Pouget [pl]            Sandrine Levet
7   2005        Angela Eiter     Emily Harrington             Akiyo Noguchi
8   2007    Angela Eiter (2)       Muriel Sarkany               Maja Vidmar
9   2009       Johanna Ernst            Kim Ja-in               Maja Vidmar
10  2011    Angela Eiter (3)            Kim Ja-in       Magdalena Röck [cs]
11  2012    Angela Eiter (4)            Kim Ja-in             Johanna Ernst
12  2014           Kim Ja-in        Mina Markovič       Magdalena Röck [cs]
13  2016      Janja Garnbret       Anak Verhoeven             Mina Markovič
14  2018        Jessica Pilz       Janja Garnbret                 Kim Ja-in
15  2019  Janja Garnbret (2)           Mia Krampl                   Ai Mori
16  2021       Seo Chae-hyun     Natalia Grossman              Laura Rogora
17  2023             Ai Mori       Janja Garnbret             Seo Chae-hyun

[7] is about Women Medal winner full names of Climbing Worldwide Championships in Disciplin LEAD

In [29]:
Dataset_Wiki_IFSC_Climbing_World_Championships[7].dtypes

Year       int64
Gold      object
Silver    object
Bronze    object
dtype: object

In [3]:
Wiki_IFSC_Climbing_World_Championships_Medal_Women_Lead_Df7 = Dataset_Wiki_IFSC_Climbing_World_Championships[7]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championships_Medal_Women_Lead_Df7
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championships_Medal_Women_Lead_Df7.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championships_Medal_Women_Lead_Df7',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [39]:
Dataset_Wiki_IFSC_Climbing_World_Championships[8]

,Year,Gold,Silver,Bronze
0,1991,Isabelle Dorsimond [fr],Agnès Brard [es],Venera Chereshneva [cs]
1,1993,Olga Bibik [fr],Isabelle Dorsimond [fr],Renata Piszczek [pl]
2,1995,Natalie Richer [fr],Cécile Avezou [fr],Renata Piszczek [pl]
3,1997,Tatiana Ruyga,Irina Zaytseva,Olga Bibik [fr]
4,1999,Olga Zakharova,Olena Ryepko [fr],Natalia Novikova [es]
5,2001,Olena Ryepko [fr],Maya Piratinskaya,Svetlana Sutkina
6,2003,Olena Ryepko [fr] (2),Tatiana Ruyga,Valentina Yurina
7,2005,Olena Ryepko [fr] (3),Valentina Yurina,Edyta Ropek [pl]
8,2007,Tatiana Ruyga (2),Edyta Ropek [pl],Valentina Yurina
9,2009 (10 m),He Cuilian,He Cuifang,Li Chunhua
10,2009 (15 m),He Cuilian (2),He Cuifang,Li Chunhua
11,2011,Maria Krasavina,Anna Tsyganova,Tamara Kuznetsova
12,2012,Yulia Levochkina,Iuliia Kaplina,Natalia Titova
13,2014,Alina Gaidamakina,Klaudia Buczek,Aleksandra Rudzińska (later with last name: Mi...
14,2016,Anna Tsyganova,Anouck Jaubert,Iuliia Kaplina
15,2018,Aleksandra Mirosław,Anna Brożek,Maria Krasavina
16,2019,Aleksandra Mirosław (2),Di Niu,Anouck Jaubert
17,2021,Natalia Kałucka,Iuliia Kaplina,Aleksandra Mirosław
18,2023,Desak Made Rita Kusuma Dewi,Emma Hunt,Aleksandra Mirosław

[8] is about Women Medal winner full names of Climbing Worldwide Championships in Disciplin SPEED

In [40]:
Dataset_Wiki_IFSC_Climbing_World_Championships[8].iloc[9,:]

Year      2009 (10 m)
Gold       He Cuilian
Silver     He Cuifang
Bronze     Li Chunhua
Name: 9, dtype: object

In [41]:
Dataset_Wiki_IFSC_Climbing_World_Championships[8].iloc[10,:]

Year         2009 (15 m)
Gold      He Cuilian (2)
Silver        He Cuifang
Bronze        Li Chunhua
Name: 10, dtype: object

2 x 2009 avec 2 hauteurs différentes 10 et 15m, même noms ds les 2 classements. deviendra donc lignes en duplicate. à supprimer

In [42]:
# Cleansing Year : delete [ ] 
Dataset_Wiki_IFSC_Climbing_World_Championships[8].iloc[9,0] = '2009'
Dataset_Wiki_IFSC_Climbing_World_Championships[8].iloc[10,0] = '2009'

In [ ]:
Dataset_Wiki_IFSC_Climbing_World_Championships[8].iloc[10,:]

In [43]:
# Delete line 10 (duplicate)
Dataset_Wiki_IFSC_Climbing_World_Championships[8].iloc[10,:] = '-'
Dataset_Wiki_IFSC_Climbing_World_Championships[8]

,Year,Gold,Silver,Bronze
0,1991,Isabelle Dorsimond [fr],Agnès Brard [es],Venera Chereshneva [cs]
1,1993,Olga Bibik [fr],Isabelle Dorsimond [fr],Renata Piszczek [pl]
2,1995,Natalie Richer [fr],Cécile Avezou [fr],Renata Piszczek [pl]
3,1997,Tatiana Ruyga,Irina Zaytseva,Olga Bibik [fr]
4,1999,Olga Zakharova,Olena Ryepko [fr],Natalia Novikova [es]
5,2001,Olena Ryepko [fr],Maya Piratinskaya,Svetlana Sutkina
6,2003,Olena Ryepko [fr] (2),Tatiana Ruyga,Valentina Yurina
7,2005,Olena Ryepko [fr] (3),Valentina Yurina,Edyta Ropek [pl]
8,2007,Tatiana Ruyga (2),Edyta Ropek [pl],Valentina Yurina
9,2009,He Cuilian,He Cuifang,Li Chunhua
10,-,-,-,-
11,2011,Maria Krasavina,Anna Tsyganova,Tamara Kuznetsova
12,2012,Yulia Levochkina,Iuliia Kaplina,Natalia Titova
13,2014,Alina Gaidamakina,Klaudia Buczek,Aleksandra Rudzińska (later with last name: Mi...
14,2016,Anna Tsyganova,Anouck Jaubert,Iuliia Kaplina
15,2018,Aleksandra Mirosław,Anna Brożek,Maria Krasavina
16,2019,Aleksandra Mirosław (2),Di Niu,Anouck Jaubert
17,2021,Natalia Kałucka,Iuliia Kaplina,Aleksandra Mirosław
18,2023,Desak Made Rita Kusuma Dewi,Emma Hunt,Aleksandra Mirosław

In [46]:
Dataset_Wiki_IFSC_Climbing_World_Championships[8].iloc[13,:]

Year                                                   2014
Gold                                      Alina Gaidamakina
Silver                                       Klaudia Buczek
Bronze    Aleksandra Rudzińska (later with last name: Mi...
Name: 13, dtype: object

In [45]:
Dataset_Wiki_IFSC_Climbing_World_Championships[8]

,Year,Gold,Silver,Bronze
0,1991,Isabelle Dorsimond [fr],Agnès Brard [es],Venera Chereshneva [cs]
1,1993,Olga Bibik [fr],Isabelle Dorsimond [fr],Renata Piszczek [pl]
2,1995,Natalie Richer [fr],Cécile Avezou [fr],Renata Piszczek [pl]
3,1997,Tatiana Ruyga,Irina Zaytseva,Olga Bibik [fr]
4,1999,Olga Zakharova,Olena Ryepko [fr],Natalia Novikova [es]
5,2001,Olena Ryepko [fr],Maya Piratinskaya,Svetlana Sutkina
6,2003,Olena Ryepko [fr] (2),Tatiana Ruyga,Valentina Yurina
7,2005,Olena Ryepko [fr] (3),Valentina Yurina,Edyta Ropek [pl]
8,2007,Tatiana Ruyga (2),Edyta Ropek [pl],Valentina Yurina
9,2009,He Cuilian,He Cuifang,Li Chunhua
10,-,-,-,-
11,2011,Maria Krasavina,Anna Tsyganova,Tamara Kuznetsova
12,2012,Yulia Levochkina,Iuliia Kaplina,Natalia Titova
13,2014,Alina Gaidamakina,Klaudia Buczek,Aleksandra Rudzińska (later with last name: Mi...
14,2016,Anna Tsyganova,Anouck Jaubert,Iuliia Kaplina
15,2018,Aleksandra Mirosław,Anna Brożek,Maria Krasavina
16,2019,Aleksandra Mirosław (2),Di Niu,Anouck Jaubert
17,2021,Natalia Kałucka,Iuliia Kaplina,Aleksandra Mirosław
18,2023,Desak Made Rita Kusuma Dewi,Emma Hunt,Aleksandra Mirosław

In [17]:
# Cleansing Name : Keep only with later last name : Mirosław
Dataset_Wiki_IFSC_Climbing_World_Championships[8].iloc[13,3] = 'Aleksandra Mirosław'

In [18]:
Dataset_Wiki_IFSC_Climbing_World_Championships[8]

,Year,Gold,Silver,Bronze
0,1991,Isabelle Dorsimond [fr],Agnès Brard [es],Venera Chereshneva [cs]
1,1993,Olga Bibik [fr],Isabelle Dorsimond [fr],Renata Piszczek [pl]
2,1995,Natalie Richer [fr],Cécile Avezou [fr],Renata Piszczek [pl]
3,1997,Tatiana Ruyga,Irina Zaytseva,Olga Bibik [fr]
4,1999,Olga Zakharova,Olena Ryepko [fr],Natalia Novikova [es]
5,2001,Olena Ryepko [fr],Maya Piratinskaya,Svetlana Sutkina
6,2003,Olena Ryepko [fr] (2),Tatiana Ruyga,Valentina Yurina
7,2005,Olena Ryepko [fr] (3),Valentina Yurina,Edyta Ropek [pl]
8,2007,Tatiana Ruyga (2),Edyta Ropek [pl],Valentina Yurina
9,2009,He Cuilian,He Cuifang,Li Chunhua
10,2009,He Cuilian (2),He Cuifang,Li Chunhua
11,2011,Maria Krasavina,Anna Tsyganova,Tamara Kuznetsova
12,2012,Yulia Levochkina,Iuliia Kaplina,Natalia Titova
13,2014,Alina Gaidamakina,Klaudia Buczek,Aleksandra Mirosław
14,2016,Anna Tsyganova,Anouck Jaubert,Iuliia Kaplina
15,2018,Aleksandra Mirosław,Anna Brożek,Maria Krasavina
16,2019,Aleksandra Mirosław (2),Di Niu,Anouck Jaubert
17,2021,Natalia Kałucka,Iuliia Kaplina,Aleksandra Mirosław
18,2023,Desak Made Rita Kusuma Dewi,Emma Hunt,Aleksandra Mirosław

In [32]:
Dataset_Wiki_IFSC_Climbing_World_Championships[8].dtypes

Year      object
Gold      object
Silver    object
Bronze    object
dtype: object

In [47]:
Wiki_IFSC_Climbing_World_Championships_Medal_Women_Speed_Df8 = Dataset_Wiki_IFSC_Climbing_World_Championships[8]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championships_Medal_Women_Speed_Df8
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(50),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championships_Medal_Women_Speed_Df8.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championships_Medal_Women_Speed_Df8',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [48]:
Dataset_Wiki_IFSC_Climbing_World_Championships[9]

,Year,Gold,Silver,Bronze
0,2001,Myriam Motteau [fr],Sandrine Levet,Nataliya Perlova [cs]
1,2003,Sandrine Levet,Nataliya Perlova [cs],Fanny Rogeaux [es]
2,2005,Olga Shalagina [fr],Julija Abramčuková [cs],Věra Kotasová-Kostruhová [cs]
3,2007,Anna Stöhr,Akiyo Noguchi,Olga Bibik
4,2009,Julija Abramčuková [cs],Olga Shalagina [fr],Anna Stöhr
5,2011,Anna Stöhr (2),Sasha DiGiulian,Juliane Wurm [de]
6,2012,Mélanie Sandoz [fr],Olga Yakovleva [cs],Anna Stöhr
7,2014,Juliane Wurm [de],Alex Puccio,Akiyo Noguchi
8,2016,Petra Klingler,Miho Nonaka,Akiyo Noguchi
9,2018,Janja Garnbret,Akiyo Noguchi,Staša Gejo
10,2019,Janja Garnbret (2),Akiyo Noguchi,Shauna Coxsey
11,2021,Natalia Grossman,Camilla Moroni [es],Staša Gejo
12,2023,Janja Garnbret (3),Oriane Bertone,Brooke Raboutou

[9] is about Women Medal winner full names of Climbing Worldwide Championships in Disciplin BOULDERING

In [34]:
Dataset_Wiki_IFSC_Climbing_World_Championships[9].dtypes

Year       int64
Gold      object
Silver    object
Bronze    object
dtype: object

In [49]:
Wiki_IFSC_Climbing_World_Championships_Medal_Women_Bouldering_Df9 = Dataset_Wiki_IFSC_Climbing_World_Championships[9]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championships_Medal_Women_Bouldering_Df9
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(50),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championships_Medal_Women_Bouldering_Df9.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championships_Medal_Women_Bouldering_Df9',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [22]:
Dataset_Wiki_IFSC_Climbing_World_Championships[10]

,Year,Gold,Silver,Bronze
0,2012,Kim Ja-in,Cécile Avezou [fr],Petra Klingler
1,2014[2],Charlotte Durif [fr],Petra Klingler,Mina Markovič
2,2016[3][22],Jelena Krasovská [cs],Claire Buhrfeind [es],Charlotte Durif [fr]
3,2018[4],Janja Garnbret,Sa Sol [de],Jessica Pilz
4,2019,Janja Garnbret (2),Akiyo Noguchi,Shauna Coxsey
5,2021,Jessica Pilz,Mia Krampl,Elnaz Rekabi
6,2023,Janja Garnbret (3),Jessica Pilz,Ai Mori

[10] is about Women Medal winner full names of Climbing Worldwide Championships in Disciplin COMBINED

In [24]:
Dataset_Wiki_IFSC_Climbing_World_Championships[10].iloc[1,:]

Year                   2014[2]
Gold      Charlotte Durif [fr]
Silver          Petra Klingler
Bronze           Mina Markovič
Name: 1, dtype: object

In [50]:
# Cleansing Year : delete [ ] 
Dataset_Wiki_IFSC_Climbing_World_Championships[10].iloc[1,:] = '2014'
Dataset_Wiki_IFSC_Climbing_World_Championships[10].iloc[2,0] = '2016'
Dataset_Wiki_IFSC_Climbing_World_Championships[10].iloc[3,0] = '2018'

In [51]:
Dataset_Wiki_IFSC_Climbing_World_Championships[10]

   Year                   Gold                 Silver                Bronze
0  2012              Kim Ja-in     Cécile Avezou [fr]        Petra Klingler
1  2014                   2014                   2014                  2014
2  2016  Jelena Krasovská [cs]  Claire Buhrfeind [es]  Charlotte Durif [fr]
3  2018         Janja Garnbret            Sa Sol [de]          Jessica Pilz
4  2019     Janja Garnbret (2)          Akiyo Noguchi         Shauna Coxsey
5  2021           Jessica Pilz             Mia Krampl          Elnaz Rekabi
6  2023     Janja Garnbret (3)           Jessica Pilz               Ai Mori

In [36]:
Dataset_Wiki_IFSC_Climbing_World_Championships[10].dtypes

Year      object
Gold      object
Silver    object
Bronze    object
dtype: object

In [52]:
Wiki_IFSC_Climbing_World_Championships_Medal_Women_Combined_Df10 = Dataset_Wiki_IFSC_Climbing_World_Championships[10]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championships_Medal_Women_Combined_Df10
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(50),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championships_Medal_Women_Combined_Df10.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championships_Medal_Women_Combined_Df10',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [136]:
Dataset_Wiki_IFSC_Climbing_World_Championships[11]

,vteIFSC Climbing World Championships,vteIFSC Climbing World Championships.1
0,1991 Frankfurt 1993 Innsbruck 1995 Geneva 1997...,1991 Frankfurt 1993 Innsbruck 1995 Geneva 1997...

[11] is duplicate of [1] > to discard !!

In [118]:
Dataset_Wiki_IFSC_Climbing_World_Championships[12]

   vteClimbing competitions                         vteClimbing competitions.1
0               Disciplines  Lead climbing (also called sport climbing) Bou...
1                  Rankings        Ranking of career IFSC victories by climber
2                      Rock  WorldIFSC IFSC Climbing World Cup IFSC Climbin...
3                     World  IFSC IFSC Climbing World Cup IFSC Climbing Wor...
4                      IFSC  IFSC Climbing World Cup IFSC Climbing World Ch...
5               Multi-sport  Summer Olympics Summer Youth Olympics World Ga...
6               Continental  IFSC African Championships African Youth Champ...
7                      IFSC  African Championships African Youth Championsh...
8               Multi-sport                         Asian Games European Games
9                  National  American Championships Austrian Championships ...
10               Individual  Sportroccia Rock Master Melloblocco Nordic Cha...
11                      Ice  World UIAA Ice Climbing World Cup UIAA Ice Cli...
12                    World  UIAA Ice Climbing World Cup UIAA Ice Climbing ...
13            Organizations  International International Federation of Spor...
14            International  International Federation of Sport Climbing (IF...
15                    Other                                       USA Climbing

[12] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [119]:
Dataset_Wiki_IFSC_Climbing_World_Championships[13]

             0                                                  1
0        World  IFSC IFSC Climbing World Cup IFSC Climbing Wor...
1         IFSC  IFSC Climbing World Cup IFSC Climbing World Ch...
2  Multi-sport  Summer Olympics Summer Youth Olympics World Ga...
3  Continental  IFSC African Championships African Youth Champ...
4         IFSC  African Championships African Youth Championsh...
5  Multi-sport                         Asian Games European Games
6     National  American Championships Austrian Championships ...
7   Individual  Sportroccia Rock Master Melloblocco Nordic Cha...

[13] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [120]:
Dataset_Wiki_IFSC_Climbing_World_Championships[14]

             0                                                  1
0         IFSC  IFSC Climbing World Cup IFSC Climbing World Ch...
1  Multi-sport  Summer Olympics Summer Youth Olympics World Ga...

[14] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [121]:
Dataset_Wiki_IFSC_Climbing_World_Championships[15]

             0                                                  1
0         IFSC  African Championships African Youth Championsh...
1  Multi-sport                         Asian Games European Games

[15] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [122]:
Dataset_Wiki_IFSC_Climbing_World_Championships[16]

       0                                                  1
0  World  UIAA Ice Climbing World Cup UIAA Ice Climbing ...

[16] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [123]:
Dataset_Wiki_IFSC_Climbing_World_Championships[17]

               0                                                  1
0  International  International Federation of Sport Climbing (IF...
1          Other                                       USA Climbing

[17] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [124]:
Dataset_Wiki_IFSC_Climbing_World_Championships[18]

,vteClimbing,vteClimbing.1
0,Types,Rock climbingDisciplines Aid Big wall Multi-pi...
1,Rock climbing,Disciplines Aid Big wall Multi-pitch Boulderin...
2,Disciplines,Aid Big wall Multi-pitch Bouldering Highball C...
3,Rock types,Crack Face Roof Slab
4,Mountaineering,Alpine Via ferrata Himalayan Alpine style Expe...
5,Other,Buildering Canyoning Crane Grass Commercial Pa...
6,Lists,Alpine clubs Climbers Piolet d'Or winners IFSC...
7,Terminology,EquipmentRock Aider Daisy chain Anchor Ascende...
8,Equipment,Rock Aider Daisy chain Anchor Ascender Croll B...
9,Rock,Aider Daisy chain Anchor Ascender Croll Belay ...
10,Ice and snow,Alpenstock Abalakov thread Bottled oxygen Cram...
11,Action,Abseiling Australian Dülfersitz Belaying Front...
12,Other,Ape index Approach shoe Clean Climbing route B...
13,Media,Magazines and journals Alpine Journal Alpinist...
14,Magazines and journals,Alpine Journal Alpinist American Alpine Journa...
15,Non-fiction films,The Alpinist El Capitan The Dawn Wall Free Sol...
16,Companies,Black Diamond CAMP Cascade Designs Deuter Earl...
17,Organizations,National Access Fund Alpine Club Alpine Club o...
18,National,Access Fund Alpine Club Alpine Club of Canada ...
19,International,International Federation of Sport Climbing (IF...
20,Portal Category Commons WikiProject,Portal Category Commons WikiProject

[18] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [125]:
Dataset_Wiki_IFSC_Climbing_World_Championships[19]

                0                                                  1
0   Rock climbing  Disciplines Aid Big wall Multi-pitch Boulderin...
1     Disciplines  Aid Big wall Multi-pitch Bouldering Highball C...
2      Rock types                               Crack Face Roof Slab
3  Mountaineering  Alpine Via ferrata Himalayan Alpine style Expe...
4           Other  Buildering Canyoning Crane Grass Commercial Pa...

[19] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [126]:
Dataset_Wiki_IFSC_Climbing_World_Championships[20]

             0                                                  1
0  Disciplines  Aid Big wall Multi-pitch Bouldering Highball C...
1   Rock types                               Crack Face Roof Slab

[20] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [127]:
Dataset_Wiki_IFSC_Climbing_World_Championships[21]

              0                                                  1
0     Equipment  Rock Aider Daisy chain Anchor Ascender Croll B...
1          Rock  Aider Daisy chain Anchor Ascender Croll Belay ...
2  Ice and snow  Alpenstock Abalakov thread Bottled oxygen Cram...
3        Action  Abseiling Australian Dülfersitz Belaying Front...
4         Other  Ape index Approach shoe Clean Climbing route B...

[21] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [128]:
Dataset_Wiki_IFSC_Climbing_World_Championships[22]

              0                                                  1
0          Rock  Aider Daisy chain Anchor Ascender Croll Belay ...
1  Ice and snow  Alpenstock Abalakov thread Bottled oxygen Cram...

[22] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [129]:
Dataset_Wiki_IFSC_Climbing_World_Championships[23]

                        0                                                  1
0  Magazines and journals  Alpine Journal Alpinist American Alpine Journa...
1       Non-fiction films  The Alpinist El Capitan The Dawn Wall Free Sol...

[23] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [130]:
Dataset_Wiki_IFSC_Climbing_World_Championships[24]

               0                                                  1
0       National  Access Fund Alpine Club Alpine Club of Canada ...
1  International  International Federation of Sport Climbing (IF...

[24] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [131]:
Dataset_Wiki_IFSC_Climbing_World_Championships[25]

,vteWorld championships,vteWorld championships.1
0,List of world sports championships,List of world sports championships
1,Olympic sports,Team Association football men men's club women...
2,Team,Association football men men's club women wome...
3,Individual,Aquatic sports Archery Athletics outdoor race ...
4,Discontinued,Basque pelota Croquet singles team Karate Lacr...
5,Paralympic sports,Team Blind football Para ice hockey men women ...
6,Team,Blind football Para ice hockey men women Wheel...
7,Individual,Archery Athletics Badminton Bobsleigh and skel...
8,Combat sports,Brazilian Jiu-Jitsu Ju-Jitsu World Championshi...
9,Cue sports,Carom billiards Three-cushion men women team F...
10,Mind sports,Backgammon Bridge Chess open women team Draugh...
11,Motorsport,Auto racing Formula E Formula One Hill climb K...
12,Auto racing,Formula E Formula One Hill climb Karting Rally...
13,Motorcycle sports,Endurance Enduro SuperEnduro Hard Enduro team ...
14,Other,Aeroplane sport Aerobatic Aerobatic GP Powerbo...
15,Other sports,Team American football men women Australian fo...
16,Team,American football men women Australian footbal...
17,Individual,Air sports ballooning gliding parachuting para...
18,Esports,Call of Duty Counter-Strike Dota 2 eSailing FI...
19,See also: World cups,See also: World cups

[25] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [132]:
Dataset_Wiki_IFSC_Climbing_World_Championships[26]

              0                                                  1
0          Team  Association football men men's club women wome...
1    Individual  Aquatic sports Archery Athletics outdoor race ...
2  Discontinued  Basque pelota Croquet singles team Karate Lacr...

[26] is NOT About Climbing > To discard

In [133]:
Dataset_Wiki_IFSC_Climbing_World_Championships[27]

            0                                                  1
0        Team  Blind football Para ice hockey men women Wheel...
1  Individual  Archery Athletics Badminton Bobsleigh and skel...

[27] is NOT About Climbing > To discard

In [134]:
Dataset_Wiki_IFSC_Climbing_World_Championships[28]

                   0                                                  1
0        Auto racing  Formula E Formula One Hill climb Karting Rally...
1  Motorcycle sports  Endurance Enduro SuperEnduro Hard Enduro team ...
2              Other  Aeroplane sport Aerobatic Aerobatic GP Powerbo...

[28] is NOT About Climbing > To discard

In [135]:
Dataset_Wiki_IFSC_Climbing_World_Championships[29]

            0                                                  1
0        Team  American football men women Australian footbal...
1  Individual  Air sports ballooning gliding parachuting para...
2     Esports  Call of Duty Counter-Strike Dota 2 eSailing FI...

[29] is NOT About Climbing > To discard