### Webscrapping with Pandas pd.read_html()  + ODBC on SQL Server with pyodbc

#### Source : Wikipedia / Sport climbing at IFSC Climbing World Youth Championships

The IFSC Climbing World Youth Championships are the annual World Youth Championships for competition climbing organized by the International Federation of Sport Climbing (IFSC). The first competition was held in Basel, Switzerland in 1992.

The competition climbing event consisted of LEAD, SPEED, BOULDERING (introduced at the 2015 championships) and combined events

There are three age groups: Juniors (18–19 years old), Youth A (16–17 years old), Youth B (14–15 years old)

In [3]:
import numpy as np
import pandas as pd
# Beautifulsoup already installed into Anaconda environment

# Librairy PyODBC for SQL Server connection
import os
import pyodbc
# setup SQL Server connection session
server = '-PCSJN\DATAVIZ'  
database = 'Climbing_Staging'
connection_string= (
                    'DRIVER={SQL Server};SERVER='
                     + server
                     + ';DATABASE='
                     + database 
                     + ';Trusted_Connection=yes'                  
                    )

# Function for injecting dataframe content into SQL Server Table
def template_SQL_insert_values(table_name,dict):
    
    columns = "("
    for k in dict.keys():
        columns += str(k) + ','
    columns = columns[:-1] ### remove last comma
    columns += ")"
    
    req = f"""INSERT INTO {table_name} {columns} VALUES {tuple(dict.values())}"""
    return req

In [4]:
### url
Wiki_IFSC_Climbing_World_Championship_Youth = "https://en.wikipedia.org/wiki/IFSC_Climbing_World_Youth_Championships"
### récuperer toutes les tables html vu sur le site (url)
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth = pd.read_html(Wiki_IFSC_Climbing_World_Championship_Youth)
type(Dataset_Wiki_IFSC_Climbing_World_Championship_Youth), len(Dataset_Wiki_IFSC_Climbing_World_Championship_Youth)

(list, 39)

##### on récupère 1 list de 39 élts

In [8]:
type(Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[0])

pandas.core.frame.DataFrame

##### > Chaque élt est un DataFrame Pandas
##### ? Quel est le contenu chacun des 39 dataframes ? Lesquelles nous interessent ?

In [9]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[0]

,IFSC Climbing World Youth Championships,IFSC Climbing World Youth Championships.1
0,Status,active
1,Genre,sporting event
2,Date(s),mid-year
3,Frequency,annual
4,Country,varying
5,Inaugurated,1992

######## [0] is dataset of summarized data about Climbing World Youth Championship dataset > NOT to Discard

In [10]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[1]

   Edition  Year               Location                        Date(s)  \
   Edition  Year               Location                        Date(s)
0      1.0  1992                  Basel               27 February 1992
1      2.0  1994                Leipzig                22 October 1994
2      3.0  1995                  Laval                 6 October 1995
3      4.0  1996                 Moscow                           1996
4      5.0  1997                   Imst               14 November 1997
5      6.0  1998                 Moscow                   16 July 1998
6      7.0  1999             Courmayeur               3 September 1999
7      8.0  2000              Amsterdam               1 September 2000
8      9.0  2001                   Imst                21–24 June 2001
9     10.0  2002               Canteleu              28 September 2002
10    11.0  2003         Veliko Tarnovo           19–21 September 2003
11    12.0  2004              Edinburgh           10–12 September 2004
12    13.0  2005                Beijing                 25 August 2005
13    14.0  2006                   Imst              24–27 August 2006
14    15.0  2007                 Ibarra              23–26 August 2007
15    16.0  2008                 Sydney              28–31 August 2008
16    17.0  2009                Valence              27–30 August 2009
17    18.0  2010              Edinburgh            9–12 September 2010
18    19.0  2011                   Imst              25–28 August 2011
19    20.0  2012              Singapore   29 August – 1 September 2012
20    21.0  2013        Central Saanich              15–19 August 2013
21    22.0  2014  Nouméa, New Caledonia           19–23 September 2014
22    23.0  2015                   Arco   28 August – 6 September 2015
23    24.0  2016              Guangzhou             7–13 November 2016
24    25.0  2017              Innsbruck  30 August – 10 September 2017
25    26.0  2018                 Moscow               9–16 August 2018
26    29.0  2019                   Arco              22–31 August 2019
27     NaN  2020               Not held                              -
28    30.0  2021               Voronezh              20–31 August 2021
29    31.0  2022                 Dallas              22–31 August 2022
30    32.0  2023                  Seoul              18–27 August 2023
31    33.0  2024                Guiyang              22–31 August 2024

   Disciplines                Notes
             L  S  B    C     Notes
0            X  -  -    -       [2]
1            X  -  -    -       [3]
2            X  -  -    -       [4]
3            X  -  -    -       NaN
4            X  -  -    -       [5]
5            X  -  -    -       [6]
6            X  -  -    -       [7]
7            X  -  -    -       [8]
8            X  X  -    -   [9][10]
9            X  X  -    -  [11][12]
10           X  -  -    -      [13]
11           X  -  -    -      [14]
12           X  X  -    -      [15]
13           X  X  -    -      [16]
14           X  X  -    -      [17]
15           X  X  -    -      [18]
16           X  X  -    -      [19]
17           X  X  -    -      [20]
18           X  X  -    -      [21]
19           X  X  -    -      [22]
20           X  X  -    -      [23]
21           X  X  -    -      [24]
22           X  X  X    X  [25][26]
23           X  X  X    X  [27][28]
24           X  X  X    X  [29][30]
25           X  X  -    -      [31]
26           X  X  X    X  [32][33]
27           -  -  -    -       NaN
28           X  X  X    X      [34]
29           X  X  X  NaN      [35]
30           X  X  X  NaN      [36]
31           X  X  X  NaN      [37]

######## [1] is dataset of List of Events (Date, Location, Program) about Climbing World Youth Championship dataset > NOT to Discard

In [11]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[2]

,Year,Gold,Silver,Bronze
0,1992,Pavel Samoiline,Faycal Natech,Elie Chevieux Ian Vickers
1,1994,Fabien Mazuer François Petit,-,Pascal Gisler
2,1995,Frederic Sarkany,Christian Bindhammer,Kalin Garbov
3,1997,Maksym Petrenko,Sylvain Millet,Thomas Feuerstein
4,1998,Yves Hasbani,Jérôme Meyer,David Gisler
5,1999,Flavio Crespi,Yves Hasbani,Patxi Usobiaga Lakunza
6,2000,Pablo Barbero Alfonso,Mykhaylo Shalagin,Nels Rosaasen
7,2001,Tomáš Mrázek,Kilian Fischhuber,Sangwon Son
8,2002,Cédric Lachat,Gérome Pouvreau,Fabien Dugit
9,2003,Eduard Marin Garcia,Jorg Verhoeven,Fabien Dugit
10,2004,Jorg Verhoeven,Eduard Marin Garcia,Dmitrii Sharafutdinov
11,2005,Daniel Winkler,Nicolas Badia,Ivan Kaurov
12,2006,Sean McColl,Thomas Neyer,Fabien Comina
13,2007,Sachi Amma,Felix Neumärker,Tsukuru Hori
14,2008,Jakob Schubert,Hyunbin Min,Martin Stráník
15,2009,Jakob Schubert,Gautier Supper,Eric Lopez Mateos
16,2010,Thomas Tauporn,Mario Lechner,Anton Mardashov
17,2011,Jure Raztresen,Edward Hamer,Stefano Ghisolfi
18,2012,Dmitrii Fakirianov,Domen Škofic,Jure Raztresen
19,2013,Dmitrii Fakirianov,Sebastian Halenke,Domen Škofic
20,2014,Bernhard Röck,Loïc Timmermans,Martin Bergant
21,2015,Bernhard Röck,Jesse Grupper,Keiichiro Korenaga
22,2016,Simon Lorenzi,Yuki Hada,Dimitri Vogt
23,2017,Yoshiyuki Ogata,Meichi Narasaki,Kai Lightner
24,2018,Meichi Narasaki,Jakub Konečný,Kai Harada
25,2019,Shuta Tanaka,Sohta Amagasa,Alistair Duval
26,2021,Hamish McArthur,Paul Jenft,Rei Kawamata
27,2022,Zento Murashita,Junta Sekiguchi,Lovro Črep
28,2023,Hannes Van Duysen,Neo Suzuki,Zento Murashita

[2] is according to the website about Medals of Junior (18–19 years old) Boys in Lead

In [12]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[2].dtypes

Year       int64
Gold      object
Silver    object
Bronze    object
dtype: object

In [13]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Boys_Lead_Df2 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[2]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Boys_Lead_Df2
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Boys_Lead_Df2.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Boys_Lead_Df2',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [14]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[3]

,Year,Gold,Silver,Bronze
0,1992,François Petit,Fabien Mazuer,Antoine Pecher
1,1994,David Carretero Perez,Anthony Lamiche Robert Mate Maksym Petrenko,-
2,1995,Sylvain Millet,Frédéric Tuscan,Markus Bock
3,1997,Julien Barbier,Yves Hasbani,François Auclair
4,1998,Alexander Meikl,Peter Szczepanski,Mykhaylo Shalagin
5,1999,Tomaz Valjavec,Mykhaylo Shalagin,Kilian Fischhuber
6,2000,Roman Felix,Fabien Dugit,Gérome Pouvreau
7,2001,Marcin Wszolek,Jorg Verhoeven,Petr Solansky
8,2002,Jorg Verhoeven,Flavien Guerimand,Christophe Treuilhe
9,2003,Sean McColl,Anthony Sapey,Romain Pagnoux
10,2004,Sean McColl,Ivan Kaurov,Fabien Comina
11,2005,Magnus Midtboe,Felix Neumärker,Sachi Amma
12,2006,Sachi Amma,Jakob Schubert,David Lama
13,2007,Jakob Schubert,Mario Lechner,Thomas Tauporn
14,2008,Mario Lechner,Thomas Tauporn,Eric Lopez Mateos
15,2009,Adam Ondra,Max Rudigier,Julian Bautista
16,2010,Jure Raztresen,Alexander Megos,Stefano Ghisolfi
17,2011,Domen Škofic,Dmitrii Fakirianov,Loïc Timmermans
18,2012,Sebastian Halenke,Semen Chesnokov,Martin Bergant
19,2013,Naoki Shimatani,Shinichiro Nomura,Bernhard Röck
20,2014,Hannes Puman,Jan-Luca Posch,Georg Parma
21,2015,Sascha Lehmann,Stefano Carnati,Hugo Parmentier
22,2016,Giorgio Bendazzoli,Kai Lightner,Taito Nakagami
23,2017,Shuta Tanaka,Nathan Martin,Mikel Asier Linacisoro Molina
24,2018,Hidemasa Nishida,Luka Potočar,Katsura Konishi
25,2019,Hidemasa Nishida,Colin Duffy,Alberto Ginés López
26,2021,Haruki Uemura,Mejdi Schalck,Timotej Romšak
27,2022,Sorato Anraku,Toby Roberts,Rikuto Inohana
28,2023,Kwon Ki-beom,Shion Omata,Auswin Aueareechit

[3]  is according to the website about Medals of Youth "A" (16–17 years old) Boys in Lead

In [15]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Boys_Lead_Df3 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[3]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Boys_Lead_Df3
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Boys_Lead_Df3.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Boys_Lead_Df3',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [16]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[4]

    Year                      Gold               Silver              Bronze
0   1992           Laurent Lanners        Olaw Mainardi     Jimmy Dubuisson
1   1994           Frédéric Tuscan    Ulrich Lindenthal          David Hume
2   1995              Chris Sharma           David Hume       Matt Engbring
3   1997              Klemen Becan          Eric Scully      Tomaz Valjavec
4   1998               Roman Felix      Clément Chabaud       Timo Preußler
5   1999               Roman Felix           Adam Stack          Remi Samyn
6   2000  Guillaume Glairon Mondet        Ethan Pringle      Jorg Verhoeven
7   2001  Guillaume Glairon Mondet          Helmut Wörz         Jan Zbranek
8   2002           Gabriele Moroni       Stepan Stráník           Jabee Kim
9   2003             Fabien Comina         Daniel Woods         Ales Jurjec
10  2004                David Lama    Blagovest Lazarov        Daniel Woods
11  2005                David Lama       Jakob Schubert      Yuriy Dzyubyak
12  2006         Eric Lopez Mateos   Arman Ter-Minasyan       Mario Lechner
13  2007                Adam Ondra     Masahiro Higuchi        Max Rudigier
14  2008                Adam Ondra         Max Rudigier     Julian Bautista
15  2009         Sebastian Halenke         Domen Škofic       Samuel Adolph
16  2010         Sebastian Halenke      Loïc Timmermans    David Firnenburg
17  2011             Bernhard Röck      Naoki Shimatani  Keiichiro Korenaga
18  2012               Anze Peharc         Hannes Puman         Georg Parma
19  2013           Stefano Carnati      Hugo Parmentier      Sascha Lehmann
20  2014              Kai Lightner        Rudolph Ruana        Minyoung Lee
21  2015                Sam Avezou       Harold Peeters      Pietro Biagini
22  2016                Sam Avezou      Katsura Konishi    Hidemasa Nishida
23  2017               Colin Duffy  Alberto Ginés López    Hidemasa Nishida
24  2018               Colin Duffy       Thomas Podolan       Kentaro Maeda
25  2019           Junta Sekiguchi        Haruki Uemura      Satone Yoshida
26  2021             Sorato Anraku           Hugo Hoyer   Dillon Countryman
27  2022               Max Bertone        Riku Ishihara    Lukas Mokrolusky
28  2023             Ryusei Hamada      Hareru Nagamori          Ryota Toda

[4] is according to the website about Medals of Youth "B" Youth B (14–15 years old) Boys in Lead

In [17]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Boys_Lead_Df4 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[4]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Boys_Lead_Df4
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Boys_Lead_Df4.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Boys_Lead_Df4',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [18]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[5]

    Year                    Gold              Silver                  Bronze
0   2001       Maksym Styenkovyy      Daniil Koźmine       Oleksandr Salimov
1   2002         Sergei Sinitcyn   Oleksandr Salimov           Dmytro Babich
2   2005  Evgenii Vaitsekhovskii  Alexander Kosterin        Eduard Ismagilov
3   2006             Sean McColl     Anatoly Skripov        Eduard Ismagilov
4   2007           Maksym Osipov       Egor Skachkov          Sergey Kokorin
5   2008     Sergey Abdrakhmanov       Maksym Osipov             QiXin Zhong
6   2009     Sergey Abdrakhmanov       Josmar Nieves       Stanislav Kokorin
7   2010           Sayat Bokanov   Bogdan Posmashnyy      Arman Ter-Minasyan
8   2011         Danyil Boldyrev     Marcin Dzieński       Sergiy Barkovskyy
9   2012        Nikita Suyushkin    Dmitrii Timofeev         Konstantin Payl
10  2013        Nikita Suyushkin      Artem Savelyev       Sergei Luzhetskii
11  2014                Jan Kriz   Sergei Luzhetskii      Alessandro Santoni
12  2015        Georgy Artamonov        John Brosler         Maksim Diachkov
13  2016        Ludovico Fossali    Pierre Rebreyend        Aleksandr Shikov
14  2017           Carlos Granja       Seungbeom Lee      Michael Finn-Henry
15  2018         Gian Luca Zodda       Noah Bratschi          Demyan Zaytsev
16  2019            Sergey Rukin        Almaz Nagaev      Rahmad Adi Mulyono
17  2021        Iaroslav Pashkov       Danila Ukolov  Lawrence Bogeschdorfer
18  2022            Shuto Fujino  Hryhorii Ilchyshyn        Leander Carmanns

[5] is according to the website about Medals of Junior (18–19 years old) Boys in Speed

In [19]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Boys_Speed_Df5 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[5]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Boys_Speed_Df5
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Boys_Speed_Df5.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Boys_Speed_Df5',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [20]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[6]

,Year,Gold,Silver,Bronze
0,2001,Johannes Lau,Andrzej Mecherzyński-Wiktor,Serguei Piniguine
1,2002,Denis Omeltchenko,Olexiy Shulga,Dmitrii Sharafutdinov
2,2005,?,Alexey Belchikov,Olexiy Zaychenko
3,2006,Maksym Osipov,Egor Skachkov,Yevgen Palladiy
4,2007,Sergey Abdrakhmanov,Gonzalo Mejia,Andres Quinteros
5,2008,Josmar Nieves,Isaac Estevez,Nic Sutton
6,2009,Leonardo Gontero,Arman Ter-Minasyan,Isaac Estevez
7,2010,Viacheslav Vedenchuk,Marcin Dzieński,Yaroslav Gontaryk
8,2011,Konstantin Payl,Artem Savelyev,Nikita Suyushkin
9,2012,Ruslan Faizullin,Sergei Luzhetskii,Georgy Artamonov
10,2013,Alessandro Santoni,Aleksandr Shikov,John Brosler
11,2014,Aleksandr Shikov,Lev Rudatskiy,Vladislav Myznikov
12,2015,Kostiantyn Pavlenko,Mehdi AliPourShenazandi,Lev Rudatskiy
13,2016,Gian Luca Zodda,Sergei Rukin,Georgii Morozov
14,2017,Sergei Rukin,Georgii Morozov,JinXin Li
15,2018,Almaz Nagaev,Jordan Fishman,Eduard Daukaev
16,2019,Iaroslav Pashkov,Jordan Fishman,Yongjun Jung
17,2021,Maksim Ryzhov,Hryhorii Ilchyshyn,Marco Rontini
18,2022,Marco Rontini,Marius Payet Gaboriaud,Samuel Watson

[6] is according to the website about Medals of Youth "A" (16–17 years old) Boys in Speed

In [21]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Boys_Speed_Df6 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[6]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Boys_Speed_Df6
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Boys_Speed_Df6.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Boys_Speed_Df6',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [22]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[7]

,Year,Gold,Silver,Bronze
0,2001,Ivan Kalinine,Olexiy Shulga,Nestor Carvajal
1,2002,Leonel De Las Salas Sean McColl,-,Vasily Kozlov
2,2005,Alexander Stepanov,Jernej Kruder,Bence Gál
3,2006,Eric Lopez Mateos,Brian Furciniti,Brian Antheunisse
4,2007,Andrey Shilenberg,Bogdan Posmashnyy,Isaac Estevez
5,2008,Viacheslav Vedenchuk,Ivan Spitsyn,Josh Levin
6,2009,Nikita Suyushkin,Artem Savelyev,Sergei Luzhetskii
7,2010,Georgy Artamonov,Sergei Luzhetskii,Alessandro Santoni
8,2011,Ruslan Faizullin,Georgy Artamonov,Alessandro Santoni
9,2012,Aleksandr Shikov,Danil Zakirov,Maksim Diachkov
10,2013,Vladislav Myznikov,Lev Rudatskiy,Kostiantyn Pavlenko
11,2014,Carlos Granja,Petr Zemliakov,Gian Luca Zodda
12,2015,Petr Zemliakov,Timur Yamaliev,Leonardo Sandrin
13,2016,Almaz Nagaev,Roman Bozhko,Danil Ogorodnikov
14,2017,Jacopo Stefani,Anton Kulba,Evgeny Kuzin
15,2018,Haram Jeon,Andrea Zappini,Ellis Ernsberger
16,2019,Hryhorii Ilchyshyn,Oliver Kuang,Dylan Le
17,2021,Kirill Koldomov,Samuel Watson,Yusuke Sugimoto
18,2022,Francesco Ponzinibio,Ginta Uegaki,Damir Toktarov

[7] is according to the website about Medals of Youth "B" Youth B (14–15 years old) Boys in Speed

In [23]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Boys_Speed_Df7 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[7]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Boys_Speed_Df7
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Boys_Speed_Df7.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Boys_Speed_Df7',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

##### Medals of Boys in SPEED : 3 Age Categories Junior (18–19 years old) [5], Youth "A" (16–17 years old) [6], Youth "B" Youth B (14–15 years old) [7]

In [24]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[8]

   Year               Gold            Silver             Bronze
0  2015       Jongwon Chon  Nicolas Pelorson        Anze Peharc
1  2016        Borna Cujic    Baptiste Ometz       William Bosi
2  2017    Yoshiyuki Ogata   Meichi Narasaki     Jan-Luca Posch
3  2018    Meichi Narasaki     Yannick Flohé         Kai Harada
4  2019      Sohta Amagasa         Leo Favot      Nathan Martin
5  2021    Hamish McArthur      Rei Kawamata         Paul Jenft
6  2022  Hannes Van Duysen   Zento Murashita    Junta Sekiguchi
7  2023    Junta Sekiguchi     Yannick Nagel  Hannes Van Duysen

[8] is according to the website about Medals of Junior (18–19 years old) Boys in Bouldering

In [25]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Boys_Bouldering_Df8 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[8]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Boys_Bouldering_Df8
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Boys_Bouldering_Df8.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Boys_Bouldering_Df8',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [26]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[9]

   Year               Gold                Silver               Bronze
0  2015    Yoshiyuki Ogata            Kai Harada      Hugo Parmentier
1  2016         Keita Dohi          Kai Lightner           Kai Harada
2  2017       Filip Schenk            Keita Dohi        Mizuki Tajima
3  2018         Sam Avezou  Eneko Carretero Cruz        Nathan Martin
4  2019        Ao Yurikusa       Hamish McArthur        Hajime Takeda
5  2021  Hannes Van Duysen       Emil Zimmermann  Thorben Perry Bloem
6  2022     Ritsu Kayotani          Toby Roberts        Sorato Anraku
7  2023     Ritsu Kayotani            Raito Kato      Thomas Lemagner

[9] is according to the website about Medals of Youth "A" (16–17 years old) Boys in Bouldering

In [27]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Boys_Bouldering_Df9 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[9]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Boys_Bouldering_Df9
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Boys_Bouldering_Df9.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Boys_Bouldering_Df9',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [28]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[10]

   Year            Gold                Silver            Bronze
0  2015    Filip Schenk            Keita Dohi  Lukas Franckaert
1  2016   Nathan Martin  Davide Marco Colombo   Katsura Konishi
2  2017    Rei Kawamata     Semen Ovchinnikov       Ryoei Nukui
3  2018    Rei Kawamata        Thomas Podolan       Ryoei Nukui
4  2019    Nichol Tomas       Junta Sekiguchi  Edvards Gruzitis
5  2021   Nikolay Rusev         Sorato Anraku     Augustine Chi
6  2022      Hugo Hoyer          Matteo Reusa   Hinata Terakawa
7  2023  Noh Hyun-seung         Ryusei Hamada   Hareru Nagamori

[10] is according to the website about Medals of Youth "B" (14–15 years old) Boys in Bouldering

In [29]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Boys_Bouldering_Df10 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[10]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Boys_Bouldering_Df10
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Boys_Bouldering_Df10.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Boys_Bouldering_Df10',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

##### Medals of Boys in BOULDERING : 3 Age Categories Junior (18–19 years old) [8], Youth "A" (16–17 years old) [9], Youth "B" Youth B (14–15 years old) [10]

In [30]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[11]

   Year                    Gold           Silver             Bronze
0  2015          Matthias Erber      Moritz Hans        Anze Peharc
1  2016          Sascha Lehmann     William Bosi   Ruben Firnenburg
2  2017         Meichi Narasaki  Yoshiyuki Ogata       Kai Lightner
3  2019           Sohta Amagasa     Shuta Tanaka      Nicolai Uznik
4  2021  Lawrence Bogeschdorfer  Hamish Mcarthur   Johannes Hofherr
5  2022         Zento Murashita  Junta Sekiguchi  Hannes Van Duysen

[11]  is according to the website about Medals of Junior (18–19 years old) Boys in Combined

In [31]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Boys_Combined_Df11 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[11]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Boys_Combined_Df11
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                       Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Boys_Combined_Df11.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Boys_Combined_Df11',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [32]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[12]

   Year              Gold           Silver               Bronze
0  2015     Carlos Granja  Hugo Parmentier    Anselm Oberdorfer
1  2016      Arsène Duval        YuFei Pan         Filip Schenk
2  2017        Sam Avezou     Filip Schenk         Petar Ivanov
3  2019       Ao Yurikusa    Hajime Takeda  Alberto Ginés López
4  2021  Edvards Gruzitis     Toby Roberts       Timotej Romšak
5  2022     Sorato Anraku     Toby Roberts       Ritsu Kayotani

 [12] is according to the website about Medals of Youth "A" (16–17 years old) Boys in Combined

In [33]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Boys_Combined_Df12 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[12]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Boys_Combined_Df12
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Boys_Combined_Df12.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Boys_Combined_Df12',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [34]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[13]

   Year               Gold         Silver                Bronze
0  2015   David Piccolruaz      YuFei Pan         DiChong Huang
1  2016         Sam Avezou  Nathan Martin  Davide Marco Colombo
2  2017  Semen Ovchinnikov   Rei Kawamata      Hidemasa Nishida
3  2019    Junta Sekiguchi   Oliver Kuang          Nichol Tomas
4  2021  Dillon Countryman  Nikolay Rusev            Timo Uznik
5  2022         Hugo Hoyer  Riku Ishihara          Kodai Yamada

 [13] is according to the website about Medals of Youth "B" (14–15 years old) Boys in Combined

In [35]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Boys_Combined_Df13 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[13]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Boys_Combined_Df13
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Boys_Combined_Df13.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Boys_Combined_Df13',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

##### Medals of Boys in COMBINED : 3 Age Categories Junior (18–19 years old) [11], Youth "A" (16–17 years old) [12], Youth "B" Youth B (14–15 years old) [13]

In [36]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[14]

    Year                 Gold              Silver                Bronze
0   1992       Muriel Sarkany      Natasa Stritih       Catherine Musso
1   1994        Marie Guillet      Irina Zaytseva      Larissa Buronova
2   1995           Liv Sansoz       Marie Guillet         Martina Cufar
3   1997       Bettina schöpf       Tatiana Ruyga     Natalia Nesterova
4   1998       Bettina schöpf  Katarina Stremfelj          Iva Hartmann
5   1999      Delphine Martin           Eva Tusar        Alexandra Eyer
6   2000       Barbara Bacher        Nastja Guzzi             Jana Oman
7   2001       Olga Shalagina       Emilie Pouget        Olga Iakovleva
8   2002        Natalija Gros       Emilie Pouget        Olga Shalagina
9   2003  Caroline Ciavaldini         Maja Vidmar         Jenny Lavarda
10  2004  Caroline Ciavaldini      Florence Pinet  Stéphanie Crouvisier
11  2005        Mina Markovič      Florence Pinet           Fanny Conan
12  2006   Katharina Saurwein          Anna Stöhr           Lisa Knoche
13  2007    Christine Schranz    Yana Chereshneva           Anne Hoarau
14  2008        Akiyo Noguchi        Juliane Wurm       Charlotte Durif
15  2009      Charlotte Durif          Ana Ogrinc        Amandine Loury
16  2010   Alexandra Ladurner     Manuela Sigrist  Dinara Fakhritdinova
17  2011       Julia Serrière       Johanna Ernst       Sasha DiGiulian
18  2012           Momoka Oda      Magdalena Röck       Katharina Posch
19  2013       Magdalena Röck     Katharina Posch            Manon Hily
20  2014             Aya Onoe        Jessica Pilz      Julia Chanourdie
21  2015       Anak Verhoeven        Jessica Pilz      Julia Chanourdie
22  2016          Margo Hayes     Hannah Schubert           Aika Tajima
23  2017     Claire Buhrfeind         Aika Tajima       Heloïse Doumont
24  2018           Vita Lukan         Nolwenn Arc          Nina Arthaud
25  2019         Laura Rogora         Nolwenn Arc       Brooke Raboutou
26  2021          Nonoha Kume       Lucija Tarkus        Camille Pouget
27  2022          Nonoha Kume       Natsuki Tanii    Michaela Smetanova
28  2023           Sara Čopar        Tomona Takao            Sana Ogura

[14] is according to the website about Medals of Junior (18–19 years old) Girls in LEAD

In [37]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Girls_Lead_Df14 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[14]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Girls_Lead_Df14
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                       Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Girls_Lead_Df14.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Girls_Lead_Df14',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [38]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[15]

,Year,Gold,Silver,Bronze
0,1992,Olga Bibik,Marie Guillet,Nataliy Pashennik
1,1994,Liv Sansoz,Mayya Piratinskaya,Irina Rouiga
2,1995,Ameli Haager,Tatiana Ruyga,Irina Rouiga
3,1996,NaN,NaN,Kathryn Embacher
4,1997,Marharyta Usatiuk,Shena Sturman,Beth Rodden
5,1998,Maria Belomestnova,Sandrine Levet,Yulia Abramchuk
6,1999,Olga Shalagina,Sandrine Levet,Barbara Bacher
7,2000,Natalija Gros,Olga Shalagina,Barbara Schranz
8,2001,Jenny Lavarda,Natalija Gros,Ekaterina Korolkova
9,2002,Caroline Ciavaldini,Angela Eiter,Stéphanie Crouvisier
10,2003,Alizée Dufraisse,Yuka Kobayashi,Angela Eiter
11,2004,Caroline Januel,Maud Ansade,Chloé Graftiaux
12,2005,Caroline Januel,Yana Chereshneva,Akiyo Noguchi
13,2006,Charlotte Durif,Akiyo Noguchi,Anne Hoarau
14,2007,Charlotte Durif,Marah Bragdon,Melissa Main
15,2008,Johanna Ernst,Katherine Choong,Alexandra Ladurner
16,2009,Katherine Choong,Hélène Janicot Julia Serrière,-
17,2010,Hélène Janicot,Katharina Posch,Magdalena Röck
18,2011,Magdalena Röck,Momoka Oda,Tina Johnsen Hafsaas
19,2012,Jessica Pilz,Anak Verhoeven,Salomé Romain
20,2013,Jessica Pilz,Anak Verhoeven,Julia Chanourdie
21,2014,Hannah Schubert,Alina Ring,Kajsa Rosen
22,2015,Janja Garnbret,Margo Hayes,Aika Tajima
23,2016,Janja Garnbret,Mia Krampl,Vita Lukan
24,2017,Ashima Shiraishi,Brooke Raboutou,Nolwenn Arc
25,2018,Brooke Raboutou,Futaba Ito,Sandra Lettner
26,2019,Nika Potapova,Natsumi Hirano,Luce Douady
27,2021,Sara Čopar,Alessia Mabboni,Liza Novak
28,2022,Aleksandra Totkova,Sara Čopar,Gaeyong Oh
29,2023,Meije Lerondel,Kim Chae-yeong,Moka Mochizuki

[15] is according to the website about Medals of Youth "A" (16–17 years old) Girls in LEAD

In [39]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[15].dtypes

Year       int64
Gold      object
Silver    object
Bronze    object
dtype: object

In [40]:
# les "nan" qui bloquent le script de population de la table ds SQL Server
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[15].iloc[3,:]

Year                  1996
Gold                   NaN
Silver                 NaN
Bronze    Kathryn Embacher
Name: 3, dtype: object

In [41]:
# Remplacer les "nan" par '-'
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[15].iloc[3,1] = '-'
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[15].iloc[3,2] = '-'
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[15]

,Year,Gold,Silver,Bronze
0,1992,Olga Bibik,Marie Guillet,Nataliy Pashennik
1,1994,Liv Sansoz,Mayya Piratinskaya,Irina Rouiga
2,1995,Ameli Haager,Tatiana Ruyga,Irina Rouiga
3,1996,-,-,Kathryn Embacher
4,1997,Marharyta Usatiuk,Shena Sturman,Beth Rodden
5,1998,Maria Belomestnova,Sandrine Levet,Yulia Abramchuk
6,1999,Olga Shalagina,Sandrine Levet,Barbara Bacher
7,2000,Natalija Gros,Olga Shalagina,Barbara Schranz
8,2001,Jenny Lavarda,Natalija Gros,Ekaterina Korolkova
9,2002,Caroline Ciavaldini,Angela Eiter,Stéphanie Crouvisier
10,2003,Alizée Dufraisse,Yuka Kobayashi,Angela Eiter
11,2004,Caroline Januel,Maud Ansade,Chloé Graftiaux
12,2005,Caroline Januel,Yana Chereshneva,Akiyo Noguchi
13,2006,Charlotte Durif,Akiyo Noguchi,Anne Hoarau
14,2007,Charlotte Durif,Marah Bragdon,Melissa Main
15,2008,Johanna Ernst,Katherine Choong,Alexandra Ladurner
16,2009,Katherine Choong,Hélène Janicot Julia Serrière,-
17,2010,Hélène Janicot,Katharina Posch,Magdalena Röck
18,2011,Magdalena Röck,Momoka Oda,Tina Johnsen Hafsaas
19,2012,Jessica Pilz,Anak Verhoeven,Salomé Romain
20,2013,Jessica Pilz,Anak Verhoeven,Julia Chanourdie
21,2014,Hannah Schubert,Alina Ring,Kajsa Rosen
22,2015,Janja Garnbret,Margo Hayes,Aika Tajima
23,2016,Janja Garnbret,Mia Krampl,Vita Lukan
24,2017,Ashima Shiraishi,Brooke Raboutou,Nolwenn Arc
25,2018,Brooke Raboutou,Futaba Ito,Sandra Lettner
26,2019,Nika Potapova,Natsumi Hirano,Luce Douady
27,2021,Sara Čopar,Alessia Mabboni,Liza Novak
28,2022,Aleksandra Totkova,Sara Čopar,Gaeyong Oh
29,2023,Meije Lerondel,Kim Chae-yeong,Moka Mochizuki

In [42]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Girls_Lead_Df15 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[15]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Girls_Lead_Df15
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Girls_Lead_Df15.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Girls_Lead_Df15',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [43]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[16]

,Year,Gold,Silver,Bronze
0,1992,Kathleen Vanbellinghen,Lydie Tuccio,Mayya Piratinskaya
1,1994,Iva Hartmann,Ameli Haager,Nicola Haager
2,1995,Katie Brown,Katarina Stremfelj,Margarita Ryzhkova
3,1997,Maria Belomestnova,Sandrine Levet,Marina Malamid
4,1998,Olga Shalagina,Natalija Gros,Katarzyna Długosz Jenny Lavarda
5,1999,Natalija Gros,Katarzyna Długosz,Nadine Ruh
6,2000,Kinga Ociepka,Emily Harrington,Alexandra Balakireva
7,2001,Kinga Ociepka,Angela Eiter,Katharina Saurwein
8,2002,Chloé Graftiaux,Yuka Kobayashi,Tori Allen Katharina Saurwein
9,2003,Silvie Rajfova,Caroline Januel,Tatiana Shelemeteva
10,2004,Charlotte Durif,Christina Schmid,Silvie Rajfova
11,2005,Charlotte Durif,Alexandra Malysheva,Juliane Wurm
12,2006,Johanna Ernst,Tiffany Hensley,Katie Mah
13,2007,Johanna Ernst,Alexandra Ladurner,Sasha DiGiulian
14,2008,Momoka Oda,Berit Schwaiger,Hélène Janicot
15,2009,Katharina Posch,Laura Michelard,Karoline Sinnhuber
16,2010,Ievgeniia Kazbekova,Anak Verhoeven,Andrea Pavlincova
17,2011,Jessica Pilz,Ievgeniia Kazbekova,Salomé Romain
18,2012,Hannah Schubert,Aika Tajima,Mona Kellner
19,2013,Aika Tajima,Emilie Gerhardt,Miwa Oba
20,2014,Janja Garnbret,Asja Gollo,Viktoriia Meshkova
21,2015,Ashima Shiraishi,Mia Krampl,Laura Rogora
22,2016,Ashima Shiraishi,Brooke Raboutou,Laura Rogora
23,2017,Ai Mori,Natsuki Tanii,Futaba Ito
24,2018,Natsuki Tanii,Nika Potapova,YueTong Zhang
25,2019,Oriane Bertone,Hana Koike,Aleksandra Totkova
26,2021,Anastasia Sanders,Meije Lerondel,Mio Nukui
27,2022,Chaeyeong Kim,Meije Leronde,Kaho Murakoshi
28,2023,Natsumi Oda,Kohana Mugishima,Geila Macia Martin

[16] is according to the website about Medals of Youth "B" (14–15 years old) Girls in LEAD

In [44]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Girls_Lead_Df16 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[16]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Girls_Lead_Df16
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Girls_Lead_Df16.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Girls_Lead_Df16',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

##### Medals of Girls in LEAD : 3 Age Categories Junior (18–19 years old) [14], Youth "A" (16–17 years old) [15], Youth "B" Youth B (14–15 years old) [16]

In [45]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[17]

    Year                  Gold                 Silver                   Bronze
0   2001        Olga Shalagina      Olga Ochtchepkova         Olesya Saulevich
1   2002     Olga Ochtchepkova         Olga Shalagina          Anna Stenkovaya
2   2005           Olga Bezhko           Yana Malkova          Anna Gallyamova
3   2006           Olga Bezhko             Anna Stöhr             Yana Malkova
4   2007      Rosmery Da Silva       Yana Chereshneva              Anne Hoarau
5   2008     Yuliya Levochkina      Alina Gaidamakina        Kseniya Polekhina
6   2009     Alina Gaidamakina  Oleksandra BUD Gusaim       Anastasiya Savisko
7   2010        Klaudia Buczek    Anastasia Ermolaeva          Dinara Usmanova
8   2011        Anna Tsyganova       Stefanie Pichler             Margot Heitz
9   2012        Anouck Jaubert        Esther Bruckner           Iuliia Kaplina
10  2013  Aleksandra Rudzinska         Anouck Jaubert  Svetlana Okolnichnikova
11  2014   Svetlana Motovilova           Andrea Rojas          Alexandra Elmer
12  2015     Patrycja Chudziak         Yana Lugovenko          Elena Timofeeva
13  2016             Daria Kan      Patrycja Chudziak          Assel Marlenova
14  2017             Daria Kan      Elizaveta Ivanova     Ekaterina Barashchuk
15  2018  Ekaterina Barashchuk      Elizaveta Ivanova           Elena Remizova
16  2019        Elena Remizova    Alejandra Contreras       Aleksandra Kalucka
17  2021      Franziska Ritter           Giulia Randi        Capucine Viglione
18  2022        Beatrice Colli        Nuria Brockfeld         Franziska Ritter

[17] is according to the website about Medals of Junior (18–19 years old) Girls in SPEED

In [46]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Girls_Speed_Df17 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[17]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Girls_Speed_Df17
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Girls_Speed_Df17.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Girls_Speed_Df17',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [47]:
Wiki_IFSC_Climbing_World_Championship_Youth[18]

'i'

[18] is according to the website about Medals of Youth "A" (16–17 years old) Girls in SPEED

In [48]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Girls_Speed_Df18 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[18]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Girls_Speed_Df18
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Girls_Speed_Df18.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Girls_Speed_Df18',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [49]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[19]

    Year                    Gold               Silver               Bronze
0   2001         Barbara Baumann  Nataliia Stoliarova     Kateryna Busheva
1   2002              Tori Allen           Anna Stöhr      Eliska Karesova
2   2005              Libby Hall    Kseniya Polekhina      Tiffany Hensley
3   2006    Dinara Fakhritdinova      Tiffany Hensley     Cassandra Zampar
4   2007    Dinara Fakhritdinova     Stefanie Pichler         Rossi Gabazú
5   2008          Taylor Clarkin    Francesca Metcalf       Cicada Jenerik
6   2009    Aleksandra Rudzinska       Anna Wagnerova        Michela Facci
7   2010             Dana Riddle      Alexandra Elmer     Valeria Baranova
8   2011       Polina Shelpakova      Alexandra Elmer  Anastasiia Golikova
9   2012           Leslie Romero         Nicole Mejia  Anastasiia Golikova
10  2013               Daria Kan  Margarita Marsanova  Anastasia Manuylova
11  2014    Ekaterina Barashchuk      Sidney Trinidad    Elena Krasovskaia
12  2015  Elisabetta Dalla Brida       Karina Gareeva    Elena Krasovskaia
13  2016          Karina Gareeva     Daria Kuznetsova    Giorgia Strazieri
14  2017         Polina Kulagina       Daria Potapova     Kamilla Kushaeva
15  2018             Jimin JEONG         Anna Calanca            Emma Hunt
16  2019            Callie Close      Nuria Brockfeld          Manon Lebon
17  2021         Daria Marciniak   Francesca Matuella       Julie Fritsche
18  2022       Kseniia Horielova    Polina Khalkevych    Maelane Villedieu

[19] is according to the website about Medals of Youth "B" (14–15 years old) Girls in SPEED

In [50]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Girls_Speed_Df19 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[19]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Girls_Speed_Df19
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Girls_Speed_Df19.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Girls_Speed_Df19',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

##### Medals of Girls in SPEED : 3 Age Categories Junior (18–19 years old) [17], Youth "A" (16–17 years old) [18], Youth "B" Youth B (14–15 years old) [19]

In [51]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[20]

   Year              Gold                Silver             Bronze
0  2015        Staša Gejo           Miho Nonaka       Jessica Pilz
1  2016       Margo Hayes            Tara Hayes  Franziska Sterrer
2  2017  Claire Buhrfeind           Maya Madere    Johanna Holfeld
3  2018     Hannah Slaney         Urska Repusic         Vita Lukan
4  2019      Laura Rogora      Natalia Grossman      Lucia Dörffel
5  2021     Naïle Meignan        Emily Phillips      Lucija Tarkus
6  2022      Zélia Avezou  Selma Elhadj Mimoune       Kylie Cullen

[20] is according to the website about Medals of Junior (18–19 years old) Girls in BOULDERING

In [52]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Girls_Bouldering_Df20 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[20]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Girls_Bouldering_Df20
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Girls_Bouldering_Df20.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Girls_Bouldering_Df20',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [53]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[21]

   Year              Gold             Silver           Bronze
0  2015    Janja Garnbret        Margo Hayes       Asja Gollo
1  2016    Janja Garnbret         Vita Lukan      Maya Madere
2  2017  Ashima Shiraishi      Luiza Emeleva  Brooke Raboutou
3  2018      Laura Rogora      Lucka Rakovec       Futaba Ito
4  2019       Luce Douady     Natsumi Hirano     Saki Kikuchi
5  2021      Zélia Avezou         Sara Čopar  Alessia Mabboni
6  2022        Sara Čopar  Michika Nagashima  Alessia Mabboni

[21] is according to the website about Medals of Youth "A" (16–17 years old) Girls in BOULDERING

In [54]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Girls_Bouldering_Df21 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[21]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Girls_Bouldering_Df21
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Girls_Bouldering_Df21.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Girls_Bouldering_Df21',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [55]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[22]

   Year               Gold             Silver           Bronze
0  2015   Ashima Shiraishi  Elena Krasovskaia       Vita Lukan
1  2016   Ashima Shiraishi         Futaba Ito  Brooke Raboutou
2  2017         Futaba Ito      Natsuki Tanii     Saki Kikuchi
3  2018      Natsuki Tanii      Naile Meignan        Hana Kudo
4  2019     Oriane Bertone       Ryu Nakagawa       Hana Koike
5  2021  Anastasia Sanders     Meije Lerondel       Sina Willy
6  2022  Anastasia Sanders        Natsumi Oda   Kaho Murakoshi

[22] is according to the website about Medals of Youth "B" (14–15 years old) Girls in BOULDERING

In [56]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Girls_Bouldering_Df22 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[20]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Girls_Bouldering_Df22
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Girls_Bouldering_Df22.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Girls_Bouldering_Df22',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

##### Medals of Girls in BOULDERING : 3 Age Categories Junior (18–19 years old) [20], Youth "A" (16–17 years old) [21], Youth "B" (14–15 years old) [22]

In [5]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[23]

   Year            Gold              Silver             Bronze
0  2015      Staša Gejo        Jessica Pilz        Kyra Condie
1  2016     Margo Hayes        Andrea Kümin  Iuliia Panteleeva
2  2017  Laura Stöckler   Iuliia Panteleeva        Margo Hayes
3  2019    Laura Rogora    Natalia Grossman      Lucia Dörffel
4  2021  Emily Phillips       Lucija Tarkus     Mahya Darabian
5  2022   Natsuki Tanii  Michaela Smetanova       Kylie Cullen

[23] is according to the website about Medals of Junior (18–19 years old) Girls in COMBINED

In [11]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Girls_Combined_Df23 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[23]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Girls_Combined_Df23
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Girls_Combined_Df23.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Junior_Girls_Combined_Df23',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [6]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[24]

   Year               Gold            Silver             Bronze
0  2015     Grace McKeehan    Janja Garnbret         Asja Gollo
1  2016  Elena Krasovskaia    Janja Garnbret      Luiza Emeleva
2  2017     Sandra Lettner  Ashima Shiraishi    Brooke Raboutou
3  2019     Natsumi Hirano        Julia Lotz     Emily Phillips
4  2021         Sara Čopar      Callie Close         Liza Novak
5  2022         Sara Čopar   Alessia Mabboni  Michika Nagashima

[24] is according to the website about Medals of Youth "A" (16–17 years old) Girls in COMBINED

In [10]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Girls_Combined_Df24 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[24]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Girls_Combined_Df24
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Girls_Combined_Df24.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_A_Girls_Combined_Df24',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

In [7]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[25]

   Year               Gold              Silver             Bronze
0  2015  Elena Krasovskaia     Brooke Raboutou       Laura Rogora
1  2016    Brooke Raboutou      Celina Schoibl       Laura Rogora
2  2017      Natsuki Tanii             Ai Mori         Futaba Ito
3  2019         Sara Čopar  Aleksandra Totkova          Heeju Noh
4  2021  Anastasia Sanders    Anastasia Kobets         Sina Willy
5  2022     Kaho Murakoshi      Meije Lerondel  Anastasia Sanders

[25] is according to the website about Medals of Youth "B" (14–15 years old) Girls in COMBINED

In [9]:
Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Girls_Combined_Df25 = Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[24]

# script de création d'une table ds SQL 
create_table = """Create TABLE Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Girls_Combined_Df25
                                   ( 
                                        id INT IDENTITY PRIMARY KEY,
                                        Year VARCHAR(100),
                                        Gold VARCHAR(100),
                                        Silver VARCHAR(100),
                                        Bronze VARCHAR(100),                                                                   
                                   ) """

# launch session
cnxn = pyodbc.connect(connection_string,autocommit=True) # no cursor.commit as Autocommit already
cursor = cnxn.cursor() 

try: 
    # load script "create " 
    cursor.execute(create_table) 
    
    # population de la table ds SQL
    for i,row in Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Girls_Combined_Df25.iterrows(): 
        row_dict=row.to_dict()
        temp = template_SQL_insert_values('Wiki_IFSC_Climbing_World_Championship_Youth_Medals_Youth_B_Girls_Combined_Df25',row_dict)
        cursor.execute(temp)
   
except Exception as err: 
    print('err:',err) 
try: 
    cursor.close()  # close session
except Exception as err: 
    print('err:',err)

##### Medals of Girls in COMBINED : 3 Age Categories Junior (18–19 years old) [23], Youth "A" (16–17 years old) [24], Youth "B" Youth B (14–15 years old) [25]

In [8]:
Dataset_Wiki_IFSC_Climbing_World_Championship_Youth[26]

   vteClimbing competitions                         vteClimbing competitions.1
0               Disciplines  Lead climbing (also called sport climbing) Bou...
1                  Rankings        Ranking of career IFSC victories by climber
2                      Rock  WorldIFSC IFSC Climbing World Cup IFSC Climbin...
3                     World  IFSC IFSC Climbing World Cup IFSC Climbing Wor...
4                      IFSC  IFSC Climbing World Cup IFSC Climbing World Ch...
5               Multi-sport  Summer Olympics Summer Youth Olympics World Ga...
6               Continental  IFSC African Championships African Youth Champ...
7                      IFSC  African Championships African Youth Championsh...
8               Multi-sport                         Asian Games European Games
9                  National  American Championships Austrian Championships ...
10               Individual  Sportroccia Rock Master Melloblocco Nordic Cha...
11                      Ice  World UIAA Ice Climbing World Cup UIAA Ice Cli...
12                    World  UIAA Ice Climbing World Cup UIAA Ice Climbing ...
13            Organizations  International International Federation of Spor...
14            International  International Federation of Sport Climbing (IF...
15                    Other                                       USA Climbing

[26] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [ ]:
Dataset_Wiki_Climbing_IFSC_World_Youth_Championship[27]

             0                                                  1
0        World  IFSC IFSC Climbing World Cup IFSC Climbing Wor...
1         IFSC  IFSC Climbing World Cup IFSC Climbing World Ch...
2  Multi-sport  Summer Olympics Summer Youth Olympics World Ga...
3  Continental  IFSC African Championships African Youth Champ...
4         IFSC  African Championships African Youth Championsh...
5  Multi-sport                         Asian Games European Games
6     National  American Championships Austrian Championships ...
7   Individual  Sportroccia Rock Master Melloblocco Nordic Cha...

[27] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [ ]:
Dataset_Wiki_Climbing_IFSC_World_Youth_Championship[28]

             0                                                  1
0         IFSC  IFSC Climbing World Cup IFSC Climbing World Ch...
1  Multi-sport  Summer Olympics Summer Youth Olympics World Ga...

[28] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [ ]:
Dataset_Wiki_Climbing_IFSC_World_Youth_Championship[29]

             0                                                  1
0         IFSC  African Championships African Youth Championsh...
1  Multi-sport                         Asian Games European Games

[29] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [ ]:
Dataset_Wiki_Climbing_IFSC_World_Youth_Championship[30]

       0                                                  1
0  World  UIAA Ice Climbing World Cup UIAA Ice Climbing ...

[30] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [ ]:
Dataset_Wiki_Climbing_IFSC_World_Youth_Championship[31]

               0                                                  1
0  International  International Federation of Sport Climbing (IF...
1          Other                                       USA Climbing

[31] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [ ]:
Dataset_Wiki_Climbing_IFSC_World_Youth_Championship[32]

,vteClimbing,vteClimbing.1
0,Types,Rock climbingDisciplines Aid Big wall Multi-pi...
1,Rock climbing,Disciplines Aid Big wall Multi-pitch Boulderin...
2,Disciplines,Aid Big wall Multi-pitch Bouldering Highball C...
3,Rock types,Crack Face Roof Slab
4,Mountaineering,Alpine Via ferrata Himalayan Alpine style Expe...
5,Other,Buildering Canyoning Crane Grass Commercial Pa...
6,Lists,Alpine clubs Climbers Piolet d'Or winners IFSC...
7,Terminology,EquipmentRock Aider Daisy chain Anchor Ascende...
8,Equipment,Rock Aider Daisy chain Anchor Ascender Croll B...
9,Rock,Aider Daisy chain Anchor Ascender Croll Belay ...
10,Ice and snow,Alpenstock Abalakov thread Bottled oxygen Cram...
11,Action,Abseiling Australian Dülfersitz Belaying Front...
12,Other,Ape index Approach shoe Clean Climbing route B...
13,Media,Magazines and journals Alpine Journal Alpinist...
14,Magazines and journals,Alpine Journal Alpinist American Alpine Journa...
15,Non-fiction films,The Alpinist El Capitan The Dawn Wall Free Sol...
16,Companies,Black Diamond CAMP Cascade Designs Deuter Earl...
17,Organizations,National Access Fund Alpine Club Alpine Club o...
18,National,Access Fund Alpine Club Alpine Club of Canada ...
19,International,International Federation of Sport Climbing (IF...
20,Portal Category Commons WikiProject,Portal Category Commons WikiProject

[32] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [ ]:
Dataset_Wiki_Climbing_IFSC_World_Youth_Championship[33]

                0                                                  1
0   Rock climbing  Disciplines Aid Big wall Multi-pitch Boulderin...
1     Disciplines  Aid Big wall Multi-pitch Bouldering Highball C...
2      Rock types                               Crack Face Roof Slab
3  Mountaineering  Alpine Via ferrata Himalayan Alpine style Expe...
4           Other  Buildering Canyoning Crane Grass Commercial Pa...

[33] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [ ]:
Dataset_Wiki_Climbing_IFSC_World_Youth_Championship[34]

             0                                                  1
0  Disciplines  Aid Big wall Multi-pitch Bouldering Highball C...
1   Rock types                               Crack Face Roof Slab

[34] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [ ]:
Dataset_Wiki_Climbing_IFSC_World_Youth_Championship[35]

              0                                                  1
0     Equipment  Rock Aider Daisy chain Anchor Ascender Croll B...
1          Rock  Aider Daisy chain Anchor Ascender Croll Belay ...
2  Ice and snow  Alpenstock Abalakov thread Bottled oxygen Cram...
3        Action  Abseiling Australian Dülfersitz Belaying Front...
4         Other  Ape index Approach shoe Clean Climbing route B...

[35] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [ ]:
Dataset_Wiki_Climbing_IFSC_World_Youth_Championship[36]

              0                                                  1
0          Rock  Aider Daisy chain Anchor Ascender Croll Belay ...
1  Ice and snow  Alpenstock Abalakov thread Bottled oxygen Cram...

[36] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [ ]:
Dataset_Wiki_Climbing_IFSC_World_Youth_Championship[37]

                        0                                                  1
0  Magazines and journals  Alpine Journal Alpinist American Alpine Journa...
1       Non-fiction films  The Alpinist El Capitan The Dawn Wall Free Sol...

[37] is duplicate from Climbing European Championships Climbing dataset > to discard !!

In [ ]:
Dataset_Wiki_Climbing_IFSC_World_Youth_Championship[38]

               0                                                  1
0       National  Access Fund Alpine Club Alpine Club of Canada ...
1  International  International Federation of Sport Climbing (IF...

[38] is duplicate from Climbing European Championships Climbing dataset > to discard !!