### Webscrapping with Pandas/BeautifulSoup

#### Source : Wikipedia / Mapping Tables of Route Climbing Grades (FR, UK, US, ...)

In [23]:
import numpy as np
import pandas as pd # Beautifulsoup installed into Anaconda environment

In [24]:
### url
Climbing_Grades_Mapping_Tables = "https://en.wikipedia.org/wiki/Grade_(climbing)"
### récuperer toutes les tables html vu sur le site (url)
Dataset_Climbing_Grades_Mapping_Tables = pd.read_html(Climbing_Grades_Mapping_Tables)
type(Dataset_Climbing_Grades_Mapping_Tables), len(Dataset_Climbing_Grades_Mapping_Tables)

(list, 11)

##### on récupère 1 list de 11 élts

In [25]:
type(Dataset_Climbing_Grades_Mapping_Tables[0])

pandas.core.frame.DataFrame

##### > Chaque élt est un DataFrame Pandas
##### ? Quel est le contenu chacun des 30 dataframes ? Lesquelles nous interessent ?

In [26]:
Dataset_Climbing_Grades_Mapping_Tables[0]

                                                    0
0                                 Part of a series on
1                                            Climbing
2   Action Directe was a major milestone in free c...
3                                               Lists
4   Climbers Piolet d'Or winners IFSC victories Eq...
5                              Types of rock climbing
6   Aid Big wall Multi-pitch Bouldering Highball C...
7                             Types of mountaineering
8   Alpine Mixed Via ferrata Himalayan Alpine styl...
9                                         Other types
10  Buildering Canyoning Crane Grass Commercial Pa...
11                                        Key actions
12  Abseiling Belaying Leading Redpointing Jumarin...
13                                          Key terms
14  Anchor First ascent FFA FFFA Grade Route Beta ...
15                                                vte

[0] is not about Climbing Grade > to Discard

In [27]:
Dataset_Climbing_Grades_Mapping_Tables[1]

   American YDS British E-grade      French sport UIAA scale Saxon scale  \
   American YDS            Tech  Adj French sport UIAA scale Saxon scale
0           3–4               1    M            1          I           I
1           5.0             NaN  NaN          NaN        NaN         NaN
2           5.1               2  NaN            2         II          II
3           5.2             NaN    D          NaN        NaN         NaN
4           5.3               3  NaN            3        III         III
5           5.4             NaN   VD           4a         IV          IV
6           5.5              4a    S           4b     IV+/V−           V
7           5.6              4b   HS           4c          V          VI
8           5.7              4c   VS           5a         V+         NaN
9           5.8             NaN  HVS           5b        VI−        VIIa
10          5.9              5a  NaN           5c         VI        VIIb
11        5.10a             NaN   E1           6a        VI+        VIIc
12        5.10b              5b  NaN          6a+       VII−         NaN
13        5.10c             NaN   E2           6b        VII       VIIIa
14        5.10d              5c  NaN          6b+       VII+       VIIIb
15        5.11a             NaN   E3       6c 6c+        NaN       VIIIc
16        5.11b             NaN  NaN       6c 6c+      VIII−         NaN
17        5.11c              6a   E4       6c 6c+        NaN         IXa
18        5.11d             NaN  NaN           7a       VIII         IXb
19        5.12a             NaN   E5          7a+      VIII+         IXc
20        5.12b              6b  NaN           7b        NaN         NaN
21        5.12c             NaN   E6          7b+        IX−          Xa
22        5.12d             NaN  NaN           7c         IX          Xb
23        5.13a              6c  NaN          7c+        IX+          Xc
24        5.13b             NaN   E7           8a         X−         XIa
25        5.13c              7a  NaN          8a+         X−         XIa
26        5.13d             NaN   E8           8b          X         XIb
27        5.14a             NaN  NaN          8b+         X+         XIc
28        5.14b              7b   E9           8c        XI−        XIIa
29        5.14c             NaN  NaN          8c+         XI        XIIb
30        5.14d             NaN  E10           9a        XI+        XIIc
31        5.15a             NaN  E11          9a+       XII−       XIIIa
32        5.15b             NaN  NaN           9b       XII−       XIIIa
33        5.15c             NaN  NaN          9b+        XII       XIIIb
34        5.15d             NaN  NaN           9c       XII+       XIIIc

   Ewbank (Aus. & NZ) Ewbank (South Africa) Scandinavian          \
   Ewbank (Aus. & NZ) Ewbank (South Africa)      Finland  Norway
0                 1–2                   1–2            1       1
1                 3–4                   3–4          NaN     NaN
2                 5–6                   5–6            2       2
3                   7                     7          NaN     NaN
4                 8–9                   8–9            3       3
5                  10                    10          NaN     NaN
6               11–12                 11–12            4       4
7                  13                    13          NaN     NaN
8               14–15                 14–15           5−      5−
9                  16                    16            5       5
10                 17                 17–18           5+      5+
11                 18                    19          NaN      6−
12                 19                    20           6−     NaN
13                 20                    21            6       6
14                NaN                    22          NaN      6+
15                 21                   NaN           6+    7− 7
16                 22                    23         7− 7    7− 7
17                 23                    24         7− 7    7− 7
18                NaN                    25         7− 7      7+
19                 24                    26           7+   7+/8−
20                 25                    27           8−      8−
21                 26                    28            8       8
22                 27                    29           8+    8/8+
23                 28                    30           9−      8+
24                 29                    31            9      9−
25                 30                    32           9+    9−/9
26                 31                    33          10−       9
27                 32                    34           10    9/9+
28                 33                    35          10+      9+
29                 34                    36          11−     10−
30                 35                    37           11      10
31                 36                    38          11+  10/10+
32                 37                    39          12−     10+
33                 38                    40           12     11−
34                 39                    41          12+      11

   Brazilian technical Polish Kurtyka
   Brazilian technical Polish Kurtyka
0                    I              I
1                I sup            NaN
2                   II             II
3               II sup            NaN
4                  NaN            III
5                  III             IV
6              III sup            NaN
7                   IV            IV+
8                  NaN             V−
9               IV sup              V
10                   V             V+
11                 NaN             VI
12                Vsup            VI+
13                  VI           VI.1
14              VI sup          VI.1+
15                  7a     VI.2 VI.2+
16                  7b     VI.2 VI.2+
17                  7c     VI.2 VI.2+
18                 NaN           VI.3
19                  8a          VI.3+
20                  8b           VI.4
21                  8c            NaN
22                  9a          VI.4+
23                  9b           VI.5
24                  9c          VI.5+
25                 10a            NaN
26                 10b           VI.6
27                 10c          VI.6+
28                 11a           VI.7
29                 11b          VI.7+
30                 11c           VI.8
31                 12a          VI.8+
32                 12b            NaN
33                 12c           VI.9
34                 13a          VI.9+

[1] is according to website about Free Climbing Climbing Grade > Not to Discard

In [28]:
Df_1_Wiki_Climbing_Grades_Mapping_Tables_Free_Climbing = Dataset_Climbing_Grades_Mapping_Tables[1]

In [29]:
Dataset_Climbing_Grades_Mapping_Tables[2]

   American V-Grade French Font Grade  Unnamed: 2 ~American  YDS ~French sport
0                VB                 3         NaN       <5.6/5.7       <5a/5b+
1               V0−                4−         NaN            5.8            5c
2                V0                 4         NaN            5.9        6a/6a+
3               V0+                4+         NaN        5.10a/b        6a+/6b
4                V1                 5         NaN        5.10c/d        6b/6b+
5                V2                5+         NaN  5.10d/5.11a/b        6b+/6c
6                V3                6A         NaN          5.11c           6c+
7               NaN               6A+         NaN          5.11d            7a
8                V4                6B         NaN          5.12a        7a/7a+
9               NaN               6B+         NaN            NaN           7a+
10               V5                6C         NaN          5.12b        7a+/7b
11              NaN               6C+         NaN            NaN            7b
12               V6                7A         NaN          5.12c           7b+
13               V7               7A+         NaN          5.12d        7b+/7c
14               V8                7B         NaN          5.13a        7c/7c+
15              NaN               7B+         NaN          5.13b        7c+/8a
16               V9                7C         NaN          5.13c        8a/8a+
17              V10               7C+         NaN          5.13d            8b
18              V11                8A         NaN          5.14a           8b+
19              V12               8A+         NaN          5.14b            8c
20              V13                8B         NaN          5.14c           8c+
21              V14               8B+         NaN          5.14d            9a
22              V15                8C         NaN          5.15a           9a+
23              V16               8C+         NaN          5.15b            9b
24              V17                9A         NaN          5.15c           9b+

[2] is according to website about Bouldering Climbing Grade > Not to Discard

In [30]:
Df_2_Wiki_Climbing_Grades_Mapping_Tables_Free_Climbing = Dataset_Climbing_Grades_Mapping_Tables[2]

In [31]:
Dataset_Climbing_Grades_Mapping_Tables[3]

   Russian  French Alpine System UIAA Overall Alpine
0       1A                     F                   I
1       1B                F+/PD−                I/II
2       2A                    PD                  II
3       2B               PD+/AD−              II/III
4       3A                    AD                 III
5       3B                AD+/D−              III/IV
6       4A                     D                  IV
7       4B                    D+                IV/V
8       5A                    TD                   V
9       5B               TD+/ED1                V/VI
10      6A  ED1/ED2 (the old ED)                  VI
11      6B     ED2 (the old ED+)                 VII

[3] is according to website about Mountaineering Climbing Grade > Not to Discard

In [32]:
Df_3_Wiki_Climbing_Grades_Mapping_Tables_Free_Climbing = Dataset_Climbing_Grades_Mapping_Tables[3]

In [33]:
Dataset_Climbing_Grades_Mapping_Tables[4]

,vteClimbing,vteClimbing.1
0,Types,Rock climbingDisciplines Aid Big wall Multi-pi...
1,Rock climbing,Disciplines Aid Big wall Multi-pitch Boulderin...
2,Disciplines,Aid Big wall Multi-pitch Bouldering Highball C...
3,Rock types,Crack Face Roof Slab
4,Mountaineering,Alpine Via ferrata Himalayan Alpine style Expe...
5,Other,Buildering Canyoning Crane Grass Commercial Pa...
6,Lists,Alpine clubs Climbers Piolet d'Or winners IFSC...
7,Terminology,EquipmentRock Aider Daisy chain Anchor Ascende...
8,Equipment,Rock Aider Daisy chain Anchor Ascender Croll B...
9,Rock,Aider Daisy chain Anchor Ascender Croll Belay ...
10,Ice and snow,Alpenstock Abalakov thread Bottled oxygen Cram...
11,Action,Abseiling Australian Dülfersitz Belaying Front...
12,Other,Ape index Approach shoe Clean Climbing route B...
13,Media,Magazines and journals Alpine Journal Alpinist...
14,Magazines and journals,Alpine Journal Alpinist American Alpine Journa...
15,Non-fiction films,The Alpinist El Capitan The Dawn Wall Free Sol...
16,Companies,Black Diamond CAMP Cascade Designs Deuter Earl...
17,Organizations,National Access Fund Alpine Club Alpine Club o...
18,National,Access Fund Alpine Club Alpine Club of Canada ...
19,International,International Federation of Sport Climbing (IF...
20,Portal Category Commons WikiProject,Portal Category Commons WikiProject

[4] is not about Climbing Grade > To Discard

In [34]:
Dataset_Climbing_Grades_Mapping_Tables[5]

                0                                                  1
0   Rock climbing  Disciplines Aid Big wall Multi-pitch Boulderin...
1     Disciplines  Aid Big wall Multi-pitch Bouldering Highball C...
2      Rock types                               Crack Face Roof Slab
3  Mountaineering  Alpine Via ferrata Himalayan Alpine style Expe...
4           Other  Buildering Canyoning Crane Grass Commercial Pa...

[5] is not about Climbing Grade > To Discard

In [35]:
Dataset_Climbing_Grades_Mapping_Tables[6]

             0                                                  1
0  Disciplines  Aid Big wall Multi-pitch Bouldering Highball C...
1   Rock types                               Crack Face Roof Slab

[6] is not about Climbing Grade > To Discard

In [36]:
Dataset_Climbing_Grades_Mapping_Tables[7]

              0                                                  1
0     Equipment  Rock Aider Daisy chain Anchor Ascender Croll B...
1          Rock  Aider Daisy chain Anchor Ascender Croll Belay ...
2  Ice and snow  Alpenstock Abalakov thread Bottled oxygen Cram...
3        Action  Abseiling Australian Dülfersitz Belaying Front...
4         Other  Ape index Approach shoe Clean Climbing route B...

[7] is not about Climbing Grade > To Discard

In [37]:
Dataset_Climbing_Grades_Mapping_Tables[8]

              0                                                  1
0          Rock  Aider Daisy chain Anchor Ascender Croll Belay ...
1  Ice and snow  Alpenstock Abalakov thread Bottled oxygen Cram...

[8] is not about Climbing Grade > To Discard

In [38]:
Dataset_Climbing_Grades_Mapping_Tables[9]

                        0                                                  1
0  Magazines and journals  Alpine Journal Alpinist American Alpine Journa...
1       Non-fiction films  The Alpinist El Capitan The Dawn Wall Free Sol...

[9] is not about Climbing Grade > To Discard

In [39]:
Dataset_Climbing_Grades_Mapping_Tables[10]

               0                                                  1
0       National  Access Fund Alpine Club Alpine Club of Canada ...
1  International  International Federation of Sport Climbing (IF...

[10]  is not about Climbing Grade > To Discard